from setuptools import setup, find_packages

setup(
    name="llm-pract",
    version="0.1.0",
    description="Q-Mini-WASM: Quantum-Classical Hybrid AI Architecture",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Q-Mini-WASM Team",
    author_email="team@q-mini-wasm.org",
    url="https://github.com/kennetholsenatm-gif/LLM_Pract",
    packages=find_packages(),
    package_data={
        "": ["*.txt", "*.md", "*.yml", "*.yaml", "*.json"],
    },
    install_requires=[
        "torch>=2.0",
        "pennylane>=0.28",
        "pennylane-qiskit>=0.28",
        "pennylane-aer>=0.28",
        "qiskit-aer>=0.12",
        "qiskit-ibmq-provider>=0.20",
        "wasmtime>=14.0",
        "pywasm>=3.0",
        "pytest>=7.4",
        "pytest-cov>=4.1",
        "bandit>=1.7",
        "safety>=2.3",
        "trivy>=0.45",
        "black>=23.7.0",
        "flake8>=6.0.0",
        "mypy>=1.4.0",
        "mkdocs>=1.5.0",
        "mkdocs-material>=9.0.0",
        "terraform>=1.8.0",
        "docker>=5.0.0",
        "docker-compose>=2.20.0",
        "prometheus-client>=0.17.0",
        "grafana-api>=0.0.1",
        "requests>=2.31",
        "boto3>=1.28",
        "google-cloud>=1.33",
        "azure-core>=1.28",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "matplotlib>=3.7.0",
        "scipy>=1.10.0",
        "sympy>=1.12.0",
        "networkx>=3.1.0",
        "scikit-learn>=1.3.0",
        "tqdm>=4.65.0",
        "rich>=13.7.0",
        "click>=8.1.0",
        "python-dotenv>=1.0.0",
        "loguru>=0.7.0",
        "pydantic>=2.5.0",
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "httpx>=0.25.0",
        "orjson>=4.2.0",
        "pydantic-settings>=2.1.0",
        "python-multipart>=0.0.6",
        "sqlalchemy>=2.0.0",
        "alembic>=1.12.0",
        "psycopg2-binary>=2.9.0",
        "redis>=5.0.0",
        "celery>=5.3.0",
        "flower>=1.0.0",
        "pytest-asyncio>=0.21.0",
        "asgi-lifespan>=1.2.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4",
            "pytest-cov>=4.1",
            "bandit>=1.7",
            "safety>=2.3",
            "black>=23.7.0",
            "flake8>=6.0.0",
            "mypy>=1.4.0",
            "mkdocs>=1.5.0",
            "mkdocs-material>=9.0.0",
        ],
        "quantum": [
            "pennylane>=0.28",
            "pennylane-qiskit>=0.28",
            "pennylane-aer>=0.28",
            "qiskit-aer>=0.12",
            "qiskit-ibmq-provider>=0.20",
        ],
        "wasm": [
            "wasmtime>=14.0",
            "pywasm>=3.0",
        ],
        "gpu": [
            "sycl>=2023.1",
            "intel-oneapi-dpcpp-python>=2023.1",
        ],
        "cloud": [
            "requests>=2.31",
            "boto3>=1.28",
            "google-cloud>=1.33",
            "azure-core>=1.28",
        ],
    },
    # Entry point reserved until qminiwasm.cli is implemented
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Quantum Computing",
        "Topic :: Software Development :: Build Tools",
    ],
    license="MIT",
    keywords="quantum machine learning AI wasm hybrid architecture",
    project_urls={
        "Documentation": "https://github.com/kennetholsenatm-gif/LLM_Pract",
        "Source": "https://github.com/kennetholsenatm-gif/LLM_Pract",
        "Tracker": "https://github.com/kennetholsenatm-gif/LLM_Pract/issues",
    },
)