import os
import subprocess
import pytest
import time
from pathlib import Path

# Test the complete DevSecOps workflow
def test_complete_workflow():
    # Check if workflow script exists
    script_path = Path("scripts/devsecops-workflow.sh")
    assert script_path.exists(), "DevSecOps workflow script should exist")
    assert script_path.stat().st_mode & 0o111, "Script should be executable")

    # Test script syntax
    result = subprocess.run(["bash", "-n", "scripts/devsecops-workflow.sh"], capture_output=True)
    assert result.returncode == 0, "Script should have valid syntax")

    # Run the workflow (this will take some time)
    print("\nRunning complete DevSecOps workflow... This may take several minutes.")
    start_time = time.time()

    try:
        result = subprocess.run(
            ["bash", "scripts/devsecops-workflow.sh"],
            capture_output=True,
            timeout=600  # 10 minute timeout
        )
    except subprocess.TimeoutExpired:
        assert False, "Workflow execution timed out after 10 minutes")

    elapsed_time = time.time() - start_time
    print(f"Workflow completed in {elapsed_time:.1f} seconds")

    # Check exit code
    assert result.returncode == 0, "Workflow should complete successfully")

    # Check output
    output = result.stdout.decode()
    assert "Starting Q-Mini-WASM complete workflow" in output, "Workflow should start properly")
    assert "Complete workflow execution completed successfully" in output, "Workflow should complete successfully")

    # Check generated files
    expected_files = [
        "stig-report.md",
        "compliance-report.md",
        "bandit-report.json",
        "bandit-report.xml",
        "safety-report.json",
        "semgrep-report.json",
        "trivy-report.json"
    ]

    for file in expected_files:
        file_path = Path(file)
        assert file_path.exists(), f"{file} should be generated by workflow")
        assert file_path.stat().st_size > 0, f"{file} should not be empty")

    # Check specific content in reports
    with open("stig-report.md") as f:
        stig_content = f.read()
        assert "STIG Requirements Check" in stig_content, "STIG report should have requirements check")
        assert "File permissions set to STIG-compliant levels" in stig_content, "STIG report should have file permissions")
        assert "No SUID/SGID bits found. Compliant." in stig_content or "Warning: SUID/SGID bits found" in stig_content, "STIG report should check SUID/SGID bits")
        assert "No world-writable files found. Compliant." in stig_content or "Warning: World-writable files found" in stig_content, "STIG report should check world-writable files")

    with open("compliance-report.md") as f:
        compliance_content = f.read()
        assert "STIG Compliance Status" in compliance_content, "Compliance report should have STIG status")
        assert "Security configuration compliant with STIG requirements" in compliance_content, "Compliance report should have security configuration")

    # Check for security scan results
    for file in ["bandit-report.json", "safety-report.json", "semgrep-report.json"]:
        with open(file) as f:
            content = f.read()
            assert "{" in content, f"{file} should be valid JSON")
            assert "results" in content or "vulnerabilities" in content, f"{file} should contain scan results")

    # Check for success messages in output
    assert "All tests passed" in output, "Workflow should show test success")
    assert "Security scan passed" in output or "Security scan found issues" in output, "Workflow should show security scan result")
    assert "STIG checks completed" in output, "Workflow should complete STIG checks")
    assert "Infrastructure deployed successfully" in output, "Workflow should deploy infrastructure")
    assert "Application deployed successfully" in output, "Workflow should deploy application")
    assert "Post-deployment tests passed" in output, "Workflow should run post-deployment tests")
    assert "Monitoring stack started successfully" in output, "Workflow should start monitoring")
    assert "Final security scan completed" in output, "Workflow should complete final security scan")
    assert "Compliance report generated" in output, "Workflow should generate compliance report")

    # Check for error handling
    assert "This script should not be run as root" not in output, "Workflow should not run as root")
    assert "All dependencies are installed" in output, "Workflow should check dependencies")

    print("\n✓ Complete DevSecOps workflow test passed successfully!")

# Test individual workflow phases
def test_workflow_phases():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    phases = [
        "Phase 1: Testing",
        "Phase 2: Security Scanning",
        "Phase 3: STIG Compliance Check",
        "Phase 4: Infrastructure Deployment",
        "Phase 5: Application Deployment",
        "Phase 6: Post-Deployment Testing",
        "Phase 7: Monitoring Setup",
        "Phase 8: Final Security Scan",
        "Phase 9: Compliance Report Generation"
    ]

    for phase in phases:
        assert phase in content, f"Workflow should include {phase}")

# Test security tools integration
def test_security_tools():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    security_tools = [
        "bandit -r src/",
        "safety check",
        "semgrep --config=auto .",
        "docker run --rm -v $(pwd):/app aquasec/trivy:latest filesystem /app"
    ]

    for tool in security_tools:
        assert tool in content, f"Workflow should include {tool}")

# Test STIG compliance checks
def test_stig_compliance():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    stig_checks = [
        "find . -type f -name \"*.sh\" -exec chmod 755 {} \\;",
        "find . -type f -name \"*.py\" -exec chmod 644 {} \\;",
        "find . -type f \\( -perm -04000 -o -perm -02000 \\)",
        "find . -type f -perm -002"
    ]

    for check in stig_checks:
        assert check in content, f"Workflow should include STIG check: {check}")

# Test infrastructure deployment
def test_infrastructure_deployment():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    terraform_commands = [
        "terraform init",
        "terraform plan",
        "terraform apply -auto-approve"
    ]

    for command in terraform_commands:
        assert command in content, f"Workflow should include Terraform command: {command}")

# Test monitoring setup
def test_monitoring_setup():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    assert "docker-compose -f monitoring/docker-compose.yml up -d" in content, "Workflow should setup monitoring")

# Test error handling
def test_error_handling():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    error_checks = [
        "if [ $? -eq 0 ]",
        "exit 1",
        "log_error",
        "log_warning"
    ]

    for check in error_checks:
        assert check in content, f"Workflow should include error handling: {check}")

# Test logging functionality
def test_logging():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    log_functions = [
        "log_info",
        "log_success",
        "log_warning",
        "log_error"
    ]

    for func in log_functions:
        assert func in content, f"Workflow should include logging function: {func}")

# Test color codes
def test_color_codes():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    colors = [
        "RED='\033[0;31m'",
        "GREEN='\033[0;32m'",
        "YELLOW='\033[1;33m'",
        "BLUE='\033[0;34m'",
        "NC='\033[0m'"
    ]

    for color in colors:
        assert color in content, f"Workflow should include color code: {color}")

# Test main function structure
def test_main_function():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    assert "main() {" in content, "Workflow should have main function")
    assert "check_dependencies" in content, "Workflow should call check_dependencies")
    assert "setup_environment" in content, "Workflow should call setup_environment")
    assert "run_complete_workflow" in content, "Workflow should call run_complete_workflow")
    assert "main \"\$@\"" in content, "Workflow should execute main function")

# Test script permissions
def test_script_permissions():
    script_path = Path("scripts/devsecops-workflow.sh")
    assert script_path.exists(), "Script should exist")
    assert script_path.stat().st_mode & 0o111, "Script should be executable")
    assert oct(script_path.stat().st_mode & 0o777) in ["0o755", "0o775"], "Script should have correct permissions")

# Test script shebang
def test_shebang():
    with open("scripts/devsecops-workflow.sh") as f:
        first_line = f.readline().strip()
        assert first_line == "#!/bin/bash", "Script should have bash shebang")

# Test script structure
def test_script_structure():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()
        assert content.count("function") >= 3, "Script should have multiple functions")
        assert content.count("Phase") >= 9, "Script should have workflow phases")
        assert content.count("log_") >= 4, "Script should have logging functions")
        assert content.count("#") >= 30, "Script should have sufficient comments")

# Test script execution time
def test_execution_time():
    # This test will actually run the script and measure execution time
    script_path = Path("scripts/devsecops-workflow.sh")
    assert script_path.exists(), "Script should exist")

    start_time = time.time()
    try:
        result = subprocess.run(
            ["bash", str(script_path)],
            capture_output=True,
            timeout=300  # 5 minute timeout for this test
        )
    except subprocess.TimeoutExpired:
        assert False, "Script execution timed out")

    elapsed_time = time.time() - start_time
    assert elapsed_time < 300, "Script should complete within 5 minutes")
    assert result.returncode == 0, "Script should complete successfully")

# Test script output
def test_script_output():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    expected_output = [
        "Starting Q-Mini-WASM complete workflow",
        "Complete workflow execution completed successfully",
        "All tests passed",
        "Security scan passed",
        "STIG checks completed",
        "Infrastructure deployed successfully",
        "Application deployed successfully",
        "Post-deployment tests passed",
        "Monitoring stack started successfully",
        "Final security scan completed",
        "Compliance report generated"
    ]

    for expected in expected_output:
        assert expected in content, f"Script should output: {expected}")

# Test script cleanup
def test_script_cleanup():
    # Check if script cleans up temporary files
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    # Check for any temporary file cleanup
    assert "rm" not in content or "trap" in content, "Script should handle cleanup properly")

# Test script documentation
def test_script_documentation():
    with open("scripts/devsecops-workflow.sh") as f:
        content = f.read()

    assert "# Q-Mini-WASM DevSecOps Complete Workflow" in content, "Script should have header documentation")
    assert "# This script runs the complete DevSecOps workflow" in content, "Script should have description")
    assert "# Colors for output" in content, "Script should document color codes")
    assert "# Logging functions" in content, "Script should document logging")
    assert "# Check if running as root" in content, "Script should document root check")
    assert "# Check dependencies" in content, "Script should document dependencies")
    assert "# Setup environment" in content, "Script should document environment setup")
    assert "# Run complete workflow" in content, "Script should document workflow")
    assert "# Main function" in content, "Script should document main function")
    assert "# Execute main function" in content, "Script should document execution")