// Managed uvicorn serving for trained artifacts (POST /api/serve/*).
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

type serveInstance struct {
	cmd       *exec.Cmd
	modelStem string
	port      int
	started   time.Time
	logBuf    *bytes.Buffer
}

var (
	serveMu     sync.Mutex
	serveActive *serveInstance
)

func serveProcessRunning() bool {
	serveMu.Lock()
	defer serveMu.Unlock()
	return serveActive != nil
}

func anyTrainingRunActive() bool {
	runManager.mu.Lock()
	defer runManager.mu.Unlock()
	for _, id := range runManager.ordered {
		if r := runManager.byID[id]; r != nil && r.Running {
			return true
		}
	}
	return false
}

func writeDockerComposeServe(stem string, port int) (relPath string, err error) {
	stem = strings.TrimSpace(stem)
	if stem == "" {
		return "", errors.New("model stem is required")
	}
	dir := filepath.Join(repoRoot, filepath.FromSlash(artifactModelDir(stem)))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	serveRel := filepath.ToSlash(filepath.Join(artifactModelDir(stem), "serve.toml"))
	portStr := strconv.Itoa(port)
	// Run from repository root so the bind mount resolves correctly.
	body := fmt.Sprintf(`# Generated by training-wui. From repository root:
#   docker compose -f %s up
# Installs the package on first start (slow); use a custom image for production.
services:
  qminiwasm-serve:
    image: python:3.11-slim
    working_dir: /repo
    volumes:
      - .:/repo
    ports:
      - "%s:%s"
    environment:
      QMINIWASM_SERVE_CONFIG: /repo/%s
    command: >-
      sh -c "pip install -q -e '/repo[training]' && python -m uvicorn qminiwasm.engine.serve:app --host 0.0.0.0 --port %s"
`,
		filepath.ToSlash(filepath.Join(artifactModelDir(stem), "docker-compose.serve.yaml")),
		portStr, portStr,
		serveRel,
		portStr,
	)
	outPath := filepath.Join(dir, "docker-compose.serve.yaml")
	if err := os.WriteFile(outPath, []byte(body), 0o644); err != nil {
		return "", err
	}
	return filepath.ToSlash(filepath.Join(artifactModelDir(stem), "docker-compose.serve.yaml")), nil
}

func handleServeStart(w http.ResponseWriter, r *http.Request) {
	if !authOK(r) {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if anyTrainingRunActive() {
		jsonErr(w, http.StatusConflict, "stop the active training run before starting the serve process")
		return
	}
	var body struct {
		ModelStem string `json:"model_stem"`
		Port      int    `json:"port"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		jsonErr(w, http.StatusBadRequest, "invalid JSON")
		return
	}
	stem := strings.TrimSpace(body.ModelStem)
	if stem == "" {
		jsonErr(w, http.StatusBadRequest, "model_stem is required")
		return
	}
	port := body.Port
	if port <= 0 {
		port = 8001
	}
	bundleAbs := filepath.Join(repoRoot, filepath.FromSlash(artifactModelDir(stem)), "agent_bundle.json")
	serveAbs := filepath.Join(repoRoot, filepath.FromSlash(artifactModelDir(stem)), "serve.toml")
	if _, err := os.Stat(bundleAbs); err != nil {
		jsonErr(w, http.StatusBadRequest, "agent_bundle.json not found — save working config from the wizard first")
		return
	}
	if _, err := os.Stat(serveAbs); err != nil {
		jsonErr(w, http.StatusBadRequest, "serve.toml not found — save working config from the wizard first")
		return
	}

	composeRel, werr := writeDockerComposeServe(stem, port)
	if werr != nil {
		jsonErr(w, http.StatusInternalServerError, werr.Error())
		return
	}

	serveMu.Lock()
	if serveActive != nil {
		serveMu.Unlock()
		jsonErr(w, http.StatusConflict, "serve process already running — call /api/serve/stop first")
		return
	}
	ctx := context.Background()
	cmd := exec.CommandContext(ctx, pythonExe, "-m", "uvicorn", "qminiwasm.engine.serve:app", "--host", "127.0.0.1", "--port", strconv.Itoa(port))
	cmd.Dir = repoRoot
	cmd.Env = append(os.Environ(), "QMINIWASM_SERVE_CONFIG="+serveAbs)
	logBuf := &bytes.Buffer{}
	cmd.Stdout = logBuf
	cmd.Stderr = logBuf
	if err := cmd.Start(); err != nil {
		serveMu.Unlock()
		jsonErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	serveActive = &serveInstance{
		cmd:       cmd,
		modelStem: stem,
		port:      port,
		started:   time.Now(),
		logBuf:    logBuf,
	}
	si := serveActive
	serveMu.Unlock()
	go func() {
		_ = si.cmd.Wait()
		serveMu.Lock()
		if serveActive == si {
			serveActive = nil
		}
		serveMu.Unlock()
	}()

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]any{
		"ok":             true,
		"model_stem":     stem,
		"port":           port,
		"pid":            cmd.Process.Pid,
		"health_url":     fmt.Sprintf("http://127.0.0.1:%d/health", port),
		"docker_compose": composeRel,
	})
}

func handleServeStop(w http.ResponseWriter, r *http.Request) {
	if !authOK(r) {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	serveMu.Lock()
	si := serveActive
	serveActive = nil
	serveMu.Unlock()
	if si == nil || si.cmd == nil || si.cmd.Process == nil {
		jsonErr(w, http.StatusNotFound, "no serve process")
		return
	}
	_ = si.cmd.Process.Kill()
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]any{"ok": true})
}

func handleServeStatus(w http.ResponseWriter, r *http.Request) {
	if !authOK(r) {
		http.Error(w, "unauthorized", http.StatusUnauthorized)
		return
	}
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	serveMu.Lock()
	si := serveActive
	serveMu.Unlock()
	if si == nil {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"running": false})
		return
	}
	tail := ""
	if si.logBuf != nil {
		tail = si.logBuf.String()
	}
	if len(tail) > 4000 {
		tail = tail[len(tail)-4000:]
	}
	out := map[string]any{
		"running":    true,
		"model_stem": si.modelStem,
		"port":       si.port,
		"started":    si.started.Format(time.RFC3339),
		"log_tail":   tail,
	}
	if si.cmd != nil && si.cmd.Process != nil {
		out["pid"] = si.cmd.Process.Pid
	}
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(out)
}
