// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: hooks.proto

package hooks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response Messages
type PreCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	StagedFiles   []string               `protobuf:"bytes,2,rep,name=staged_files,json=stagedFiles,proto3" json:"staged_files,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCommitRequest) Reset() {
	*x = PreCommitRequest{}
	mi := &file_hooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCommitRequest) ProtoMessage() {}

func (x *PreCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCommitRequest.ProtoReflect.Descriptor instead.
func (*PreCommitRequest) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{0}
}

func (x *PreCommitRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PreCommitRequest) GetStagedFiles() []string {
	if x != nil {
		return x.StagedFiles
	}
	return nil
}

func (x *PreCommitRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type CommitMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessageRequest) Reset() {
	*x = CommitMessageRequest{}
	mi := &file_hooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessageRequest) ProtoMessage() {}

func (x *CommitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessageRequest.ProtoReflect.Descriptor instead.
func (*CommitMessageRequest) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{1}
}

func (x *CommitMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitMessageRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type PrePushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	Remote        string                 `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePushRequest) Reset() {
	*x = PrePushRequest{}
	mi := &file_hooks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePushRequest) ProtoMessage() {}

func (x *PrePushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePushRequest.ProtoReflect.Descriptor instead.
func (*PrePushRequest) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{2}
}

func (x *PrePushRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PrePushRequest) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *PrePushRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type PostCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoPath      string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Branch        string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommitRequest) Reset() {
	*x = PostCommitRequest{}
	mi := &file_hooks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommitRequest) ProtoMessage() {}

func (x *PostCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommitRequest.ProtoReflect.Descriptor instead.
func (*PostCommitRequest) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{3}
}

func (x *PostCommitRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PostCommitRequest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *PostCommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PostCommitRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type PostMergeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoPath       string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	MergeCommit    string                 `protobuf:"bytes,2,opt,name=merge_commit,json=mergeCommit,proto3" json:"merge_commit,omitempty"`
	MergedBranches []string               `protobuf:"bytes,3,rep,name=merged_branches,json=mergedBranches,proto3" json:"merged_branches,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostMergeRequest) Reset() {
	*x = PostMergeRequest{}
	mi := &file_hooks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMergeRequest) ProtoMessage() {}

func (x *PostMergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMergeRequest.ProtoReflect.Descriptor instead.
func (*PostMergeRequest) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{4}
}

func (x *PostMergeRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PostMergeRequest) GetMergeCommit() string {
	if x != nil {
		return x.MergeCommit
	}
	return ""
}

func (x *PostMergeRequest) GetMergedBranches() []string {
	if x != nil {
		return x.MergedBranches
	}
	return nil
}

type HookConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HookType      string                 `protobuf:"bytes,1,opt,name=hook_type,json=hookType,proto3" json:"hook_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookConfigRequest) Reset() {
	*x = HookConfigRequest{}
	mi := &file_hooks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookConfigRequest) ProtoMessage() {}

func (x *HookConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookConfigRequest.ProtoReflect.Descriptor instead.
func (*HookConfigRequest) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{5}
}

func (x *HookConfigRequest) GetHookType() string {
	if x != nil {
		return x.HookType
	}
	return ""
}

type HookConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Checks        []*HookCheck           `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	Actions       []*HookAction          `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookConfigResponse) Reset() {
	*x = HookConfigResponse{}
	mi := &file_hooks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookConfigResponse) ProtoMessage() {}

func (x *HookConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookConfigResponse.ProtoReflect.Descriptor instead.
func (*HookConfigResponse) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{6}
}

func (x *HookConfigResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HookConfigResponse) GetChecks() []*HookCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *HookConfigResponse) GetActions() []*HookAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type UpdateHookConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HookType      string                 `protobuf:"bytes,1,opt,name=hook_type,json=hookType,proto3" json:"hook_type,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Checks        []*HookCheck           `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHookConfigRequest) Reset() {
	*x = UpdateHookConfigRequest{}
	mi := &file_hooks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHookConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHookConfigRequest) ProtoMessage() {}

func (x *UpdateHookConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHookConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateHookConfigRequest) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateHookConfigRequest) GetHookType() string {
	if x != nil {
		return x.HookType
	}
	return ""
}

func (x *UpdateHookConfigRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateHookConfigRequest) GetChecks() []*HookCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_hooks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{8}
}

func (x *HookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HookResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *HookResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *HookResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HookCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookCheck) Reset() {
	*x = HookCheck{}
	mi := &file_hooks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookCheck) ProtoMessage() {}

func (x *HookCheck) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookCheck.ProtoReflect.Descriptor instead.
func (*HookCheck) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{9}
}

func (x *HookCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HookCheck) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HookCheck) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HookCheck) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type HookAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookAction) Reset() {
	*x = HookAction{}
	mi := &file_hooks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookAction) ProtoMessage() {}

func (x *HookAction) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookAction.ProtoReflect.Descriptor instead.
func (*HookAction) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{10}
}

func (x *HookAction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HookAction) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HookAction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HookAction) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_hooks_proto protoreflect.FileDescriptor

const file_hooks_proto_rawDesc = "" +
	"\n" +
	"\vhooks.proto\x12\x05hooks\"j\n" +
	"\x10PreCommitRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12!\n" +
	"\fstaged_files\x18\x02 \x03(\tR\vstagedFiles\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\"H\n" +
	"\x14CommitMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"]\n" +
	"\x0ePrePushRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x16\n" +
	"\x06remote\x18\x02 \x01(\tR\x06remote\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\"\x83\x01\n" +
	"\x11PostCommitRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\"{\n" +
	"\x10PostMergeRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12!\n" +
	"\fmerge_commit\x18\x02 \x01(\tR\vmergeCommit\x12'\n" +
	"\x0fmerged_branches\x18\x03 \x03(\tR\x0emergedBranches\"0\n" +
	"\x11HookConfigRequest\x12\x1b\n" +
	"\thook_type\x18\x01 \x01(\tR\bhookType\"\x85\x01\n" +
	"\x12HookConfigResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12(\n" +
	"\x06checks\x18\x02 \x03(\v2\x10.hooks.HookCheckR\x06checks\x12+\n" +
	"\aactions\x18\x03 \x03(\v2\x11.hooks.HookActionR\aactions\"z\n" +
	"\x17UpdateHookConfigRequest\x12\x1b\n" +
	"\thook_type\x18\x01 \x01(\tR\bhookType\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12(\n" +
	"\x06checks\x18\x03 \x03(\v2\x10.hooks.HookCheckR\x06checks\"\xf2\x01\n" +
	"\fHookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.hooks.HookResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\tHookCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"x\n" +
	"\n" +
	"HookAction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired2\xed\x03\n" +
	"\vHookService\x12@\n" +
	"\x10ExecutePreCommit\x12\x17.hooks.PreCommitRequest\x1a\x13.hooks.HookResponse\x12I\n" +
	"\x15ValidateCommitMessage\x12\x1b.hooks.CommitMessageRequest\x1a\x13.hooks.HookResponse\x12<\n" +
	"\x0eExecutePrePush\x12\x15.hooks.PrePushRequest\x1a\x13.hooks.HookResponse\x12B\n" +
	"\x11ExecutePostCommit\x12\x18.hooks.PostCommitRequest\x1a\x13.hooks.HookResponse\x12@\n" +
	"\x10ExecutePostMerge\x12\x17.hooks.PostMergeRequest\x1a\x13.hooks.HookResponse\x12D\n" +
	"\rGetHookConfig\x12\x18.hooks.HookConfigRequest\x1a\x19.hooks.HookConfigResponse\x12G\n" +
	"\x10UpdateHookConfig\x12\x1e.hooks.UpdateHookConfigRequest\x1a\x13.hooks.HookResponseB2Z0github.com/q_mini_wasm_v2/gateway/pkg/grpc/hooksb\x06proto3"

var (
	file_hooks_proto_rawDescOnce sync.Once
	file_hooks_proto_rawDescData []byte
)

func file_hooks_proto_rawDescGZIP() []byte {
	file_hooks_proto_rawDescOnce.Do(func() {
		file_hooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hooks_proto_rawDesc), len(file_hooks_proto_rawDesc)))
	})
	return file_hooks_proto_rawDescData
}

var file_hooks_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_hooks_proto_goTypes = []any{
	(*PreCommitRequest)(nil),        // 0: hooks.PreCommitRequest
	(*CommitMessageRequest)(nil),    // 1: hooks.CommitMessageRequest
	(*PrePushRequest)(nil),          // 2: hooks.PrePushRequest
	(*PostCommitRequest)(nil),       // 3: hooks.PostCommitRequest
	(*PostMergeRequest)(nil),        // 4: hooks.PostMergeRequest
	(*HookConfigRequest)(nil),       // 5: hooks.HookConfigRequest
	(*HookConfigResponse)(nil),      // 6: hooks.HookConfigResponse
	(*UpdateHookConfigRequest)(nil), // 7: hooks.UpdateHookConfigRequest
	(*HookResponse)(nil),            // 8: hooks.HookResponse
	(*HookCheck)(nil),               // 9: hooks.HookCheck
	(*HookAction)(nil),              // 10: hooks.HookAction
	nil,                             // 11: hooks.HookResponse.MetadataEntry
}
var file_hooks_proto_depIdxs = []int32{
	9,  // 0: hooks.HookConfigResponse.checks:type_name -> hooks.HookCheck
	10, // 1: hooks.HookConfigResponse.actions:type_name -> hooks.HookAction
	9,  // 2: hooks.UpdateHookConfigRequest.checks:type_name -> hooks.HookCheck
	11, // 3: hooks.HookResponse.metadata:type_name -> hooks.HookResponse.MetadataEntry
	0,  // 4: hooks.HookService.ExecutePreCommit:input_type -> hooks.PreCommitRequest
	1,  // 5: hooks.HookService.ValidateCommitMessage:input_type -> hooks.CommitMessageRequest
	2,  // 6: hooks.HookService.ExecutePrePush:input_type -> hooks.PrePushRequest
	3,  // 7: hooks.HookService.ExecutePostCommit:input_type -> hooks.PostCommitRequest
	4,  // 8: hooks.HookService.ExecutePostMerge:input_type -> hooks.PostMergeRequest
	5,  // 9: hooks.HookService.GetHookConfig:input_type -> hooks.HookConfigRequest
	7,  // 10: hooks.HookService.UpdateHookConfig:input_type -> hooks.UpdateHookConfigRequest
	8,  // 11: hooks.HookService.ExecutePreCommit:output_type -> hooks.HookResponse
	8,  // 12: hooks.HookService.ValidateCommitMessage:output_type -> hooks.HookResponse
	8,  // 13: hooks.HookService.ExecutePrePush:output_type -> hooks.HookResponse
	8,  // 14: hooks.HookService.ExecutePostCommit:output_type -> hooks.HookResponse
	8,  // 15: hooks.HookService.ExecutePostMerge:output_type -> hooks.HookResponse
	6,  // 16: hooks.HookService.GetHookConfig:output_type -> hooks.HookConfigResponse
	8,  // 17: hooks.HookService.UpdateHookConfig:output_type -> hooks.HookResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hooks_proto_init() }
func file_hooks_proto_init() {
	if File_hooks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hooks_proto_rawDesc), len(file_hooks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hooks_proto_goTypes,
		DependencyIndexes: file_hooks_proto_depIdxs,
		MessageInfos:      file_hooks_proto_msgTypes,
	}.Build()
	File_hooks_proto = out.File
	file_hooks_proto_goTypes = nil
	file_hooks_proto_depIdxs = nil
}
