// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: hooks.proto

package hooks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HookService_ExecutePreCommit_FullMethodName      = "/hooks.HookService/ExecutePreCommit"
	HookService_ValidateCommitMessage_FullMethodName = "/hooks.HookService/ValidateCommitMessage"
	HookService_ExecutePrePush_FullMethodName        = "/hooks.HookService/ExecutePrePush"
	HookService_ExecutePostCommit_FullMethodName     = "/hooks.HookService/ExecutePostCommit"
	HookService_ExecutePostMerge_FullMethodName      = "/hooks.HookService/ExecutePostMerge"
	HookService_GetHookConfig_FullMethodName         = "/hooks.HookService/GetHookConfig"
	HookService_UpdateHookConfig_FullMethodName      = "/hooks.HookService/UpdateHookConfig"
)

// HookServiceClient is the client API for HookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HookService provides gRPC interface for executing hooks
type HookServiceClient interface {
	// Execute pre-commit hook
	ExecutePreCommit(ctx context.Context, in *PreCommitRequest, opts ...grpc.CallOption) (*HookResponse, error)
	// Validate commit message format
	ValidateCommitMessage(ctx context.Context, in *CommitMessageRequest, opts ...grpc.CallOption) (*HookResponse, error)
	// Execute pre-push hook
	ExecutePrePush(ctx context.Context, in *PrePushRequest, opts ...grpc.CallOption) (*HookResponse, error)
	// Execute post-commit hook
	ExecutePostCommit(ctx context.Context, in *PostCommitRequest, opts ...grpc.CallOption) (*HookResponse, error)
	// Execute post-merge hook
	ExecutePostMerge(ctx context.Context, in *PostMergeRequest, opts ...grpc.CallOption) (*HookResponse, error)
	// Get hook configuration
	GetHookConfig(ctx context.Context, in *HookConfigRequest, opts ...grpc.CallOption) (*HookConfigResponse, error)
	// Update hook configuration
	UpdateHookConfig(ctx context.Context, in *UpdateHookConfigRequest, opts ...grpc.CallOption) (*HookResponse, error)
}

type hookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHookServiceClient(cc grpc.ClientConnInterface) HookServiceClient {
	return &hookServiceClient{cc}
}

func (c *hookServiceClient) ExecutePreCommit(ctx context.Context, in *PreCommitRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, HookService_ExecutePreCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) ValidateCommitMessage(ctx context.Context, in *CommitMessageRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, HookService_ValidateCommitMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) ExecutePrePush(ctx context.Context, in *PrePushRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, HookService_ExecutePrePush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) ExecutePostCommit(ctx context.Context, in *PostCommitRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, HookService_ExecutePostCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) ExecutePostMerge(ctx context.Context, in *PostMergeRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, HookService_ExecutePostMerge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) GetHookConfig(ctx context.Context, in *HookConfigRequest, opts ...grpc.CallOption) (*HookConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookConfigResponse)
	err := c.cc.Invoke(ctx, HookService_GetHookConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hookServiceClient) UpdateHookConfig(ctx context.Context, in *UpdateHookConfigRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, HookService_UpdateHookConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HookServiceServer is the server API for HookService service.
// All implementations must embed UnimplementedHookServiceServer
// for forward compatibility.
//
// HookService provides gRPC interface for executing hooks
type HookServiceServer interface {
	// Execute pre-commit hook
	ExecutePreCommit(context.Context, *PreCommitRequest) (*HookResponse, error)
	// Validate commit message format
	ValidateCommitMessage(context.Context, *CommitMessageRequest) (*HookResponse, error)
	// Execute pre-push hook
	ExecutePrePush(context.Context, *PrePushRequest) (*HookResponse, error)
	// Execute post-commit hook
	ExecutePostCommit(context.Context, *PostCommitRequest) (*HookResponse, error)
	// Execute post-merge hook
	ExecutePostMerge(context.Context, *PostMergeRequest) (*HookResponse, error)
	// Get hook configuration
	GetHookConfig(context.Context, *HookConfigRequest) (*HookConfigResponse, error)
	// Update hook configuration
	UpdateHookConfig(context.Context, *UpdateHookConfigRequest) (*HookResponse, error)
	mustEmbedUnimplementedHookServiceServer()
}

// UnimplementedHookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHookServiceServer struct{}

func (UnimplementedHookServiceServer) ExecutePreCommit(context.Context, *PreCommitRequest) (*HookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePreCommit not implemented")
}
func (UnimplementedHookServiceServer) ValidateCommitMessage(context.Context, *CommitMessageRequest) (*HookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCommitMessage not implemented")
}
func (UnimplementedHookServiceServer) ExecutePrePush(context.Context, *PrePushRequest) (*HookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePrePush not implemented")
}
func (UnimplementedHookServiceServer) ExecutePostCommit(context.Context, *PostCommitRequest) (*HookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePostCommit not implemented")
}
func (UnimplementedHookServiceServer) ExecutePostMerge(context.Context, *PostMergeRequest) (*HookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePostMerge not implemented")
}
func (UnimplementedHookServiceServer) GetHookConfig(context.Context, *HookConfigRequest) (*HookConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHookConfig not implemented")
}
func (UnimplementedHookServiceServer) UpdateHookConfig(context.Context, *UpdateHookConfigRequest) (*HookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHookConfig not implemented")
}
func (UnimplementedHookServiceServer) mustEmbedUnimplementedHookServiceServer() {}
func (UnimplementedHookServiceServer) testEmbeddedByValue()                     {}

// UnsafeHookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HookServiceServer will
// result in compilation errors.
type UnsafeHookServiceServer interface {
	mustEmbedUnimplementedHookServiceServer()
}

func RegisterHookServiceServer(s grpc.ServiceRegistrar, srv HookServiceServer) {
	// If the following call panics, it indicates UnimplementedHookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HookService_ServiceDesc, srv)
}

func _HookService_ExecutePreCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).ExecutePreCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HookService_ExecutePreCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).ExecutePreCommit(ctx, req.(*PreCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_ValidateCommitMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).ValidateCommitMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HookService_ValidateCommitMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).ValidateCommitMessage(ctx, req.(*CommitMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_ExecutePrePush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).ExecutePrePush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HookService_ExecutePrePush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).ExecutePrePush(ctx, req.(*PrePushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_ExecutePostCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).ExecutePostCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HookService_ExecutePostCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).ExecutePostCommit(ctx, req.(*PostCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_ExecutePostMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).ExecutePostMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HookService_ExecutePostMerge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).ExecutePostMerge(ctx, req.(*PostMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_GetHookConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).GetHookConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HookService_GetHookConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).GetHookConfig(ctx, req.(*HookConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HookService_UpdateHookConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHookConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).UpdateHookConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HookService_UpdateHookConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).UpdateHookConfig(ctx, req.(*UpdateHookConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HookService_ServiceDesc is the grpc.ServiceDesc for HookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hooks.HookService",
	HandlerType: (*HookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecutePreCommit",
			Handler:    _HookService_ExecutePreCommit_Handler,
		},
		{
			MethodName: "ValidateCommitMessage",
			Handler:    _HookService_ValidateCommitMessage_Handler,
		},
		{
			MethodName: "ExecutePrePush",
			Handler:    _HookService_ExecutePrePush_Handler,
		},
		{
			MethodName: "ExecutePostCommit",
			Handler:    _HookService_ExecutePostCommit_Handler,
		},
		{
			MethodName: "ExecutePostMerge",
			Handler:    _HookService_ExecutePostMerge_Handler,
		},
		{
			MethodName: "GetHookConfig",
			Handler:    _HookService_GetHookConfig_Handler,
		},
		{
			MethodName: "UpdateHookConfig",
			Handler:    _HookService_UpdateHookConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hooks.proto",
}
