# CMake generated Testfile for 
# Source directory: C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2
# Build directory: C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(q_mini_wasm_v2_dll_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Debug/q_mini_wasm_v2_dll_test.exe")
  set_tests_properties(q_mini_wasm_v2_dll_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;335;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(q_mini_wasm_v2_dll_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Release/q_mini_wasm_v2_dll_test.exe")
  set_tests_properties(q_mini_wasm_v2_dll_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;335;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(q_mini_wasm_v2_dll_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/MinSizeRel/q_mini_wasm_v2_dll_test.exe")
  set_tests_properties(q_mini_wasm_v2_dll_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;335;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(q_mini_wasm_v2_dll_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/RelWithDebInfo/q_mini_wasm_v2_dll_test.exe")
  set_tests_properties(q_mini_wasm_v2_dll_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;335;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
else()
  add_test(q_mini_wasm_v2_dll_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(q_mini_wasm_v2_dll_api_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Debug/q_mini_wasm_v2_dll_api_test.exe")
  set_tests_properties(q_mini_wasm_v2_dll_api_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;343;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(q_mini_wasm_v2_dll_api_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Release/q_mini_wasm_v2_dll_api_test.exe")
  set_tests_properties(q_mini_wasm_v2_dll_api_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;343;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(q_mini_wasm_v2_dll_api_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/MinSizeRel/q_mini_wasm_v2_dll_api_test.exe")
  set_tests_properties(q_mini_wasm_v2_dll_api_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;343;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(q_mini_wasm_v2_dll_api_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/RelWithDebInfo/q_mini_wasm_v2_dll_api_test.exe")
  set_tests_properties(q_mini_wasm_v2_dll_api_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;343;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
else()
  add_test(q_mini_wasm_v2_dll_api_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(q_mini_wasm_v2_tests "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Debug/q_mini_wasm_v2_tests.exe")
  set_tests_properties(q_mini_wasm_v2_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;347;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(q_mini_wasm_v2_tests "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Release/q_mini_wasm_v2_tests.exe")
  set_tests_properties(q_mini_wasm_v2_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;347;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(q_mini_wasm_v2_tests "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/MinSizeRel/q_mini_wasm_v2_tests.exe")
  set_tests_properties(q_mini_wasm_v2_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;347;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(q_mini_wasm_v2_tests "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/RelWithDebInfo/q_mini_wasm_v2_tests.exe")
  set_tests_properties(q_mini_wasm_v2_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;347;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
else()
  add_test(q_mini_wasm_v2_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(q_mini_wasm_v2_network_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Debug/q_mini_wasm_v2_network_test.exe")
  set_tests_properties(q_mini_wasm_v2_network_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;348;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(q_mini_wasm_v2_network_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Release/q_mini_wasm_v2_network_test.exe")
  set_tests_properties(q_mini_wasm_v2_network_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;348;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(q_mini_wasm_v2_network_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/MinSizeRel/q_mini_wasm_v2_network_test.exe")
  set_tests_properties(q_mini_wasm_v2_network_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;348;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(q_mini_wasm_v2_network_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/RelWithDebInfo/q_mini_wasm_v2_network_test.exe")
  set_tests_properties(q_mini_wasm_v2_network_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;348;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
else()
  add_test(q_mini_wasm_v2_network_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(q_mini_wasm_v2_remediation_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Debug/q_mini_wasm_v2_remediation_test.exe")
  set_tests_properties(q_mini_wasm_v2_remediation_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;349;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(q_mini_wasm_v2_remediation_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Release/q_mini_wasm_v2_remediation_test.exe")
  set_tests_properties(q_mini_wasm_v2_remediation_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;349;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(q_mini_wasm_v2_remediation_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/MinSizeRel/q_mini_wasm_v2_remediation_test.exe")
  set_tests_properties(q_mini_wasm_v2_remediation_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;349;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(q_mini_wasm_v2_remediation_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/RelWithDebInfo/q_mini_wasm_v2_remediation_test.exe")
  set_tests_properties(q_mini_wasm_v2_remediation_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;349;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
else()
  add_test(q_mini_wasm_v2_remediation_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(q_mini_wasm_v2_betti_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Debug/q_mini_wasm_v2_betti_test.exe")
  set_tests_properties(q_mini_wasm_v2_betti_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;350;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(q_mini_wasm_v2_betti_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/Release/q_mini_wasm_v2_betti_test.exe")
  set_tests_properties(q_mini_wasm_v2_betti_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;350;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(q_mini_wasm_v2_betti_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/MinSizeRel/q_mini_wasm_v2_betti_test.exe")
  set_tests_properties(q_mini_wasm_v2_betti_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;350;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(q_mini_wasm_v2_betti_test "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/build_final/RelWithDebInfo/q_mini_wasm_v2_betti_test.exe")
  set_tests_properties(q_mini_wasm_v2_betti_test PROPERTIES  _BACKTRACE_TRIPLES "C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;350;add_test;C:/GitHub/q_mini_wasm_v2/q_mini_wasm_v2/CMakeLists.txt;0;")
else()
  add_test(q_mini_wasm_v2_betti_test NOT_AVAILABLE)
endif()
