// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: training_engine.proto

package trainingrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse_EngineState int32

const (
	StatusResponse_ENGINE_STATE_UNSPECIFIED StatusResponse_EngineState = 0
	StatusResponse_ENGINE_STATE_IDLE        StatusResponse_EngineState = 1
	StatusResponse_ENGINE_STATE_STARTING    StatusResponse_EngineState = 2
	StatusResponse_ENGINE_STATE_RUNNING     StatusResponse_EngineState = 3
	StatusResponse_ENGINE_STATE_STOPPING    StatusResponse_EngineState = 4
	StatusResponse_ENGINE_STATE_STOPPED     StatusResponse_EngineState = 5
	StatusResponse_ENGINE_STATE_FAILED      StatusResponse_EngineState = 6
)

// Enum value maps for StatusResponse_EngineState.
var (
	StatusResponse_EngineState_name = map[int32]string{
		0: "ENGINE_STATE_UNSPECIFIED",
		1: "ENGINE_STATE_IDLE",
		2: "ENGINE_STATE_STARTING",
		3: "ENGINE_STATE_RUNNING",
		4: "ENGINE_STATE_STOPPING",
		5: "ENGINE_STATE_STOPPED",
		6: "ENGINE_STATE_FAILED",
	}
	StatusResponse_EngineState_value = map[string]int32{
		"ENGINE_STATE_UNSPECIFIED": 0,
		"ENGINE_STATE_IDLE":        1,
		"ENGINE_STATE_STARTING":    2,
		"ENGINE_STATE_RUNNING":     3,
		"ENGINE_STATE_STOPPING":    4,
		"ENGINE_STATE_STOPPED":     5,
		"ENGINE_STATE_FAILED":      6,
	}
)

func (x StatusResponse_EngineState) Enum() *StatusResponse_EngineState {
	p := new(StatusResponse_EngineState)
	*p = x
	return p
}

func (x StatusResponse_EngineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_EngineState) Descriptor() protoreflect.EnumDescriptor {
	return file_training_engine_proto_enumTypes[0].Descriptor()
}

func (StatusResponse_EngineState) Type() protoreflect.EnumType {
	return &file_training_engine_proto_enumTypes[0]
}

func (x StatusResponse_EngineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_EngineState.Descriptor instead.
func (StatusResponse_EngineState) EnumDescriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{10, 0}
}

// Hugging Face tabular fetch + encoding hints for the native C++ training engine.
type HfDatasetParams struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DatasetId         string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	ConfigName        string                 `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Split             string                 `protobuf:"bytes,3,opt,name=split,proto3" json:"split,omitempty"`
	Revision          string                 `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	NumSamples        uint32                 `protobuf:"varint,5,opt,name=num_samples,json=numSamples,proto3" json:"num_samples,omitempty"`
	MeshBlendFraction float64                `protobuf:"fixed64,6,opt,name=mesh_blend_fraction,json=meshBlendFraction,proto3" json:"mesh_blend_fraction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HfDatasetParams) Reset() {
	*x = HfDatasetParams{}
	mi := &file_training_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HfDatasetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HfDatasetParams) ProtoMessage() {}

func (x *HfDatasetParams) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HfDatasetParams.ProtoReflect.Descriptor instead.
func (*HfDatasetParams) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{0}
}

func (x *HfDatasetParams) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *HfDatasetParams) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *HfDatasetParams) GetSplit() string {
	if x != nil {
		return x.Split
	}
	return ""
}

func (x *HfDatasetParams) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *HfDatasetParams) GetNumSamples() uint32 {
	if x != nil {
		return x.NumSamples
	}
	return 0
}

func (x *HfDatasetParams) GetMeshBlendFraction() float64 {
	if x != nil {
		return x.MeshBlendFraction
	}
	return 0
}

// Automated cascade curriculum: teacher fit to PTQTP on student to heal vs frozen teacher to optional gate.
type CascadeCurriculumLoopParams struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Enabled               bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MaxHealRounds         uint32                 `protobuf:"varint,2,opt,name=max_heal_rounds,json=maxHealRounds,proto3" json:"max_heal_rounds,omitempty"`
	TeacherCheckpointPath string                 `protobuf:"bytes,3,opt,name=teacher_checkpoint_path,json=teacherCheckpointPath,proto3" json:"teacher_checkpoint_path,omitempty"`
	PtqtpNumPlanes        uint32                 `protobuf:"varint,4,opt,name=ptqtp_num_planes,json=ptqtpNumPlanes,proto3" json:"ptqtp_num_planes,omitempty"`
	GateTargetValMse      float64                `protobuf:"fixed64,5,opt,name=gate_target_val_mse,json=gateTargetValMse,proto3" json:"gate_target_val_mse,omitempty"`
	GateMaxTpemMib        float64                `protobuf:"fixed64,6,opt,name=gate_max_tpem_mib,json=gateMaxTpemMib,proto3" json:"gate_max_tpem_mib,omitempty"`
	RunTaxonomyLinter     bool                   `protobuf:"varint,7,opt,name=run_taxonomy_linter,json=runTaxonomyLinter,proto3" json:"run_taxonomy_linter,omitempty"`
	HealLearningRateScale float64                `protobuf:"fixed64,8,opt,name=heal_learning_rate_scale,json=healLearningRateScale,proto3" json:"heal_learning_rate_scale,omitempty"`
	TeacherEpochFraction  float64                `protobuf:"fixed64,9,opt,name=teacher_epoch_fraction,json=teacherEpochFraction,proto3" json:"teacher_epoch_fraction,omitempty"`
	HealEpochsPerRound    uint32                 `protobuf:"varint,10,opt,name=heal_epochs_per_round,json=healEpochsPerRound,proto3" json:"heal_epochs_per_round,omitempty"`
	MaxCurriculumCycles   uint32                 `protobuf:"varint,11,opt,name=max_curriculum_cycles,json=maxCurriculumCycles,proto3" json:"max_curriculum_cycles,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CascadeCurriculumLoopParams) Reset() {
	*x = CascadeCurriculumLoopParams{}
	mi := &file_training_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CascadeCurriculumLoopParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CascadeCurriculumLoopParams) ProtoMessage() {}

func (x *CascadeCurriculumLoopParams) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CascadeCurriculumLoopParams.ProtoReflect.Descriptor instead.
func (*CascadeCurriculumLoopParams) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{1}
}

func (x *CascadeCurriculumLoopParams) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CascadeCurriculumLoopParams) GetMaxHealRounds() uint32 {
	if x != nil {
		return x.MaxHealRounds
	}
	return 0
}

func (x *CascadeCurriculumLoopParams) GetTeacherCheckpointPath() string {
	if x != nil {
		return x.TeacherCheckpointPath
	}
	return ""
}

func (x *CascadeCurriculumLoopParams) GetPtqtpNumPlanes() uint32 {
	if x != nil {
		return x.PtqtpNumPlanes
	}
	return 0
}

func (x *CascadeCurriculumLoopParams) GetGateTargetValMse() float64 {
	if x != nil {
		return x.GateTargetValMse
	}
	return 0
}

func (x *CascadeCurriculumLoopParams) GetGateMaxTpemMib() float64 {
	if x != nil {
		return x.GateMaxTpemMib
	}
	return 0
}

func (x *CascadeCurriculumLoopParams) GetRunTaxonomyLinter() bool {
	if x != nil {
		return x.RunTaxonomyLinter
	}
	return false
}

func (x *CascadeCurriculumLoopParams) GetHealLearningRateScale() float64 {
	if x != nil {
		return x.HealLearningRateScale
	}
	return 0
}

func (x *CascadeCurriculumLoopParams) GetTeacherEpochFraction() float64 {
	if x != nil {
		return x.TeacherEpochFraction
	}
	return 0
}

func (x *CascadeCurriculumLoopParams) GetHealEpochsPerRound() uint32 {
	if x != nil {
		return x.HealEpochsPerRound
	}
	return 0
}

func (x *CascadeCurriculumLoopParams) GetMaxCurriculumCycles() uint32 {
	if x != nil {
		return x.MaxCurriculumCycles
	}
	return 0
}

// One row of [[training_phases]] (Unified Training Matrix). See docs/ARCHITECTURE_WHITEPAPERS.md.
type TrainingPhaseParams struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Epochs                 uint32                 `protobuf:"varint,2,opt,name=epochs,proto3" json:"epochs,omitempty"`
	Supervised             bool                   `protobuf:"varint,3,opt,name=supervised,proto3" json:"supervised,omitempty"`
	CascadeRl              bool                   `protobuf:"varint,4,opt,name=cascade_rl,json=cascadeRl,proto3" json:"cascade_rl,omitempty"`
	FreezeModelBackbone    bool                   `protobuf:"varint,5,opt,name=freeze_model_backbone,json=freezeModelBackbone,proto3" json:"freeze_model_backbone,omitempty"`
	RouterOnly             bool                   `protobuf:"varint,6,opt,name=router_only,json=routerOnly,proto3" json:"router_only,omitempty"`
	CascadePolicyOptimizer string                 `protobuf:"bytes,7,opt,name=cascade_policy_optimizer,json=cascadePolicyOptimizer,proto3" json:"cascade_policy_optimizer,omitempty"`
	CispoClipEpsilon       *float64               `protobuf:"fixed64,8,opt,name=cispo_clip_epsilon,json=cispoClipEpsilon,proto3,oneof" json:"cispo_clip_epsilon,omitempty"`
	CascadeMopdLambda      *float64               `protobuf:"fixed64,9,opt,name=cascade_mopd_lambda,json=cascadeMopdLambda,proto3,oneof" json:"cascade_mopd_lambda,omitempty"`
	TequilaDeadzone        *float64               `protobuf:"fixed64,10,opt,name=tequila_deadzone,json=tequilaDeadzone,proto3,oneof" json:"tequila_deadzone,omitempty"`
	FreezeTernaryExperts   bool                   `protobuf:"varint,11,opt,name=freeze_ternary_experts,json=freezeTernaryExperts,proto3" json:"freeze_ternary_experts,omitempty"`
	// Absolute path: MOPD teacher interchange v2 for this phase (optional).
	MopdTeacherCheckpointPath string `protobuf:"bytes,12,opt,name=mopd_teacher_checkpoint_path,json=mopdTeacherCheckpointPath,proto3" json:"mopd_teacher_checkpoint_path,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TrainingPhaseParams) Reset() {
	*x = TrainingPhaseParams{}
	mi := &file_training_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingPhaseParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingPhaseParams) ProtoMessage() {}

func (x *TrainingPhaseParams) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingPhaseParams.ProtoReflect.Descriptor instead.
func (*TrainingPhaseParams) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{2}
}

func (x *TrainingPhaseParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainingPhaseParams) GetEpochs() uint32 {
	if x != nil {
		return x.Epochs
	}
	return 0
}

func (x *TrainingPhaseParams) GetSupervised() bool {
	if x != nil {
		return x.Supervised
	}
	return false
}

func (x *TrainingPhaseParams) GetCascadeRl() bool {
	if x != nil {
		return x.CascadeRl
	}
	return false
}

func (x *TrainingPhaseParams) GetFreezeModelBackbone() bool {
	if x != nil {
		return x.FreezeModelBackbone
	}
	return false
}

func (x *TrainingPhaseParams) GetRouterOnly() bool {
	if x != nil {
		return x.RouterOnly
	}
	return false
}

func (x *TrainingPhaseParams) GetCascadePolicyOptimizer() string {
	if x != nil {
		return x.CascadePolicyOptimizer
	}
	return ""
}

func (x *TrainingPhaseParams) GetCispoClipEpsilon() float64 {
	if x != nil && x.CispoClipEpsilon != nil {
		return *x.CispoClipEpsilon
	}
	return 0
}

func (x *TrainingPhaseParams) GetCascadeMopdLambda() float64 {
	if x != nil && x.CascadeMopdLambda != nil {
		return *x.CascadeMopdLambda
	}
	return 0
}

func (x *TrainingPhaseParams) GetTequilaDeadzone() float64 {
	if x != nil && x.TequilaDeadzone != nil {
		return *x.TequilaDeadzone
	}
	return 0
}

func (x *TrainingPhaseParams) GetFreezeTernaryExperts() bool {
	if x != nil {
		return x.FreezeTernaryExperts
	}
	return false
}

func (x *TrainingPhaseParams) GetMopdTeacherCheckpointPath() string {
	if x != nil {
		return x.MopdTeacherCheckpointPath
	}
	return ""
}

type TrainingConfig struct {
	state                  protoimpl.MessageState       `protogen:"open.v1"`
	RunId                  string                       `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	DatasetUri             string                       `protobuf:"bytes,2,opt,name=dataset_uri,json=datasetUri,proto3" json:"dataset_uri,omitempty"`
	ModelUri               string                       `protobuf:"bytes,3,opt,name=model_uri,json=modelUri,proto3" json:"model_uri,omitempty"`
	Epochs                 uint32                       `protobuf:"varint,4,opt,name=epochs,proto3" json:"epochs,omitempty"`
	BatchSize              uint32                       `protobuf:"varint,5,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	MicroBatchSize         uint32                       `protobuf:"varint,6,opt,name=micro_batch_size,json=microBatchSize,proto3" json:"micro_batch_size,omitempty"`
	PrefetchDepth          uint32                       `protobuf:"varint,7,opt,name=prefetch_depth,json=prefetchDepth,proto3" json:"prefetch_depth,omitempty"`
	ComputeSlots           uint32                       `protobuf:"varint,8,opt,name=compute_slots,json=computeSlots,proto3" json:"compute_slots,omitempty"`
	WorkerThreads          uint32                       `protobuf:"varint,9,opt,name=worker_threads,json=workerThreads,proto3" json:"worker_threads,omitempty"`
	LearningRate           float64                      `protobuf:"fixed64,10,opt,name=learning_rate,json=learningRate,proto3" json:"learning_rate,omitempty"`
	Seed                   uint64                       `protobuf:"varint,11,opt,name=seed,proto3" json:"seed,omitempty"`
	TaxonomyTier           string                       `protobuf:"bytes,12,opt,name=taxonomy_tier,json=taxonomyTier,proto3" json:"taxonomy_tier,omitempty"`
	PrecisionPolicy        string                       `protobuf:"bytes,13,opt,name=precision_policy,json=precisionPolicy,proto3" json:"precision_policy,omitempty"`
	CheckpointSavePath     string                       `protobuf:"bytes,14,opt,name=checkpoint_save_path,json=checkpointSavePath,proto3" json:"checkpoint_save_path,omitempty"`
	CheckpointBestPath     string                       `protobuf:"bytes,15,opt,name=checkpoint_best_path,json=checkpointBestPath,proto3" json:"checkpoint_best_path,omitempty"`
	CheckpointLatestPath   string                       `protobuf:"bytes,16,opt,name=checkpoint_latest_path,json=checkpointLatestPath,proto3" json:"checkpoint_latest_path,omitempty"`
	DModel                 uint32                       `protobuf:"varint,17,opt,name=d_model,json=dModel,proto3" json:"d_model,omitempty"`
	IoDModel               uint32                       `protobuf:"varint,18,opt,name=io_d_model,json=ioDModel,proto3" json:"io_d_model,omitempty"`
	NumTernaryBlocks       uint32                       `protobuf:"varint,19,opt,name=num_ternary_blocks,json=numTernaryBlocks,proto3" json:"num_ternary_blocks,omitempty"`
	Hf                     *HfDatasetParams             `protobuf:"bytes,20,opt,name=hf,proto3" json:"hf,omitempty"`
	CascadeLoop            *CascadeCurriculumLoopParams `protobuf:"bytes,21,opt,name=cascade_loop,json=cascadeLoop,proto3" json:"cascade_loop,omitempty"`
	UseNativeEngineOnly    bool                         `protobuf:"varint,22,opt,name=use_native_engine_only,json=useNativeEngineOnly,proto3" json:"use_native_engine_only,omitempty"`
	TrainingPhases         []*TrainingPhaseParams       `protobuf:"bytes,23,rep,name=training_phases,json=trainingPhases,proto3" json:"training_phases,omitempty"`
	CascadePolicyOptimizer string                       `protobuf:"bytes,24,opt,name=cascade_policy_optimizer,json=cascadePolicyOptimizer,proto3" json:"cascade_policy_optimizer,omitempty"`
	CispoClipEpsilon       float64                      `protobuf:"fixed64,25,opt,name=cispo_clip_epsilon,json=cispoClipEpsilon,proto3" json:"cispo_clip_epsilon,omitempty"`
	AttentionBackend       string                       `protobuf:"bytes,26,opt,name=attention_backend,json=attentionBackend,proto3" json:"attention_backend,omitempty"`
	// GRPO/CISPO trajectory batch size for native LibTorch toy cascade RL ([cascade] group_size in TOML). Default 4.
	CascadeRlGroupSize uint32 `protobuf:"varint,27,opt,name=cascade_rl_group_size,json=cascadeRlGroupSize,proto3" json:"cascade_rl_group_size,omitempty"`
	// Native LibTorch Bloch attention: sequence length for broadcast token + learnable pos_embed (after stem). 0 = default 8 when attention_backend=bloch.
	NativeBlochSeqLen uint32 `protobuf:"varint,28,opt,name=native_bloch_seq_len,json=nativeBlochSeqLen,proto3" json:"native_bloch_seq_len,omitempty"`
	// Native Bloch head count; 0 = default 4 (adjusted down so d_model is divisible). Ignored when attention_backend != bloch.
	NativeBlochNumHeads uint32 `protobuf:"varint,29,opt,name=native_bloch_num_heads,json=nativeBlochNumHeads,proto3" json:"native_bloch_num_heads,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TrainingConfig) Reset() {
	*x = TrainingConfig{}
	mi := &file_training_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingConfig) ProtoMessage() {}

func (x *TrainingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingConfig.ProtoReflect.Descriptor instead.
func (*TrainingConfig) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{3}
}

func (x *TrainingConfig) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TrainingConfig) GetDatasetUri() string {
	if x != nil {
		return x.DatasetUri
	}
	return ""
}

func (x *TrainingConfig) GetModelUri() string {
	if x != nil {
		return x.ModelUri
	}
	return ""
}

func (x *TrainingConfig) GetEpochs() uint32 {
	if x != nil {
		return x.Epochs
	}
	return 0
}

func (x *TrainingConfig) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *TrainingConfig) GetMicroBatchSize() uint32 {
	if x != nil {
		return x.MicroBatchSize
	}
	return 0
}

func (x *TrainingConfig) GetPrefetchDepth() uint32 {
	if x != nil {
		return x.PrefetchDepth
	}
	return 0
}

func (x *TrainingConfig) GetComputeSlots() uint32 {
	if x != nil {
		return x.ComputeSlots
	}
	return 0
}

func (x *TrainingConfig) GetWorkerThreads() uint32 {
	if x != nil {
		return x.WorkerThreads
	}
	return 0
}

func (x *TrainingConfig) GetLearningRate() float64 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

func (x *TrainingConfig) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *TrainingConfig) GetTaxonomyTier() string {
	if x != nil {
		return x.TaxonomyTier
	}
	return ""
}

func (x *TrainingConfig) GetPrecisionPolicy() string {
	if x != nil {
		return x.PrecisionPolicy
	}
	return ""
}

func (x *TrainingConfig) GetCheckpointSavePath() string {
	if x != nil {
		return x.CheckpointSavePath
	}
	return ""
}

func (x *TrainingConfig) GetCheckpointBestPath() string {
	if x != nil {
		return x.CheckpointBestPath
	}
	return ""
}

func (x *TrainingConfig) GetCheckpointLatestPath() string {
	if x != nil {
		return x.CheckpointLatestPath
	}
	return ""
}

func (x *TrainingConfig) GetDModel() uint32 {
	if x != nil {
		return x.DModel
	}
	return 0
}

func (x *TrainingConfig) GetIoDModel() uint32 {
	if x != nil {
		return x.IoDModel
	}
	return 0
}

func (x *TrainingConfig) GetNumTernaryBlocks() uint32 {
	if x != nil {
		return x.NumTernaryBlocks
	}
	return 0
}

func (x *TrainingConfig) GetHf() *HfDatasetParams {
	if x != nil {
		return x.Hf
	}
	return nil
}

func (x *TrainingConfig) GetCascadeLoop() *CascadeCurriculumLoopParams {
	if x != nil {
		return x.CascadeLoop
	}
	return nil
}

func (x *TrainingConfig) GetUseNativeEngineOnly() bool {
	if x != nil {
		return x.UseNativeEngineOnly
	}
	return false
}

func (x *TrainingConfig) GetTrainingPhases() []*TrainingPhaseParams {
	if x != nil {
		return x.TrainingPhases
	}
	return nil
}

func (x *TrainingConfig) GetCascadePolicyOptimizer() string {
	if x != nil {
		return x.CascadePolicyOptimizer
	}
	return ""
}

func (x *TrainingConfig) GetCispoClipEpsilon() float64 {
	if x != nil {
		return x.CispoClipEpsilon
	}
	return 0
}

func (x *TrainingConfig) GetAttentionBackend() string {
	if x != nil {
		return x.AttentionBackend
	}
	return ""
}

func (x *TrainingConfig) GetCascadeRlGroupSize() uint32 {
	if x != nil {
		return x.CascadeRlGroupSize
	}
	return 0
}

func (x *TrainingConfig) GetNativeBlochSeqLen() uint32 {
	if x != nil {
		return x.NativeBlochSeqLen
	}
	return 0
}

func (x *TrainingConfig) GetNativeBlochNumHeads() uint32 {
	if x != nil {
		return x.NativeBlochNumHeads
	}
	return 0
}

type StartTrainingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TrainingConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrainingRequest) Reset() {
	*x = StartTrainingRequest{}
	mi := &file_training_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrainingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrainingRequest) ProtoMessage() {}

func (x *StartTrainingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrainingRequest.ProtoReflect.Descriptor instead.
func (*StartTrainingRequest) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{4}
}

func (x *StartTrainingRequest) GetConfig() *TrainingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type NativeColdStartMemoryEstimate struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ParameterBytesFp32         uint64                 `protobuf:"varint,1,opt,name=parameter_bytes_fp32,json=parameterBytesFp32,proto3" json:"parameter_bytes_fp32,omitempty"`
	AdamStateBytesFp32         uint64                 `protobuf:"varint,2,opt,name=adam_state_bytes_fp32,json=adamStateBytesFp32,proto3" json:"adam_state_bytes_fp32,omitempty"`
	ActivationScratchBytesHint uint64                 `protobuf:"varint,3,opt,name=activation_scratch_bytes_hint,json=activationScratchBytesHint,proto3" json:"activation_scratch_bytes_hint,omitempty"`
	FormulaSummary             string                 `protobuf:"bytes,4,opt,name=formula_summary,json=formulaSummary,proto3" json:"formula_summary,omitempty"`
	EffectiveDModel            uint32                 `protobuf:"varint,5,opt,name=effective_d_model,json=effectiveDModel,proto3" json:"effective_d_model,omitempty"`
	EffectiveIoDModel          uint32                 `protobuf:"varint,6,opt,name=effective_io_d_model,json=effectiveIoDModel,proto3" json:"effective_io_d_model,omitempty"`
	EffectiveNumTernaryBlocks  uint32                 `protobuf:"varint,7,opt,name=effective_num_ternary_blocks,json=effectiveNumTernaryBlocks,proto3" json:"effective_num_ternary_blocks,omitempty"`
	BatchSize                  uint32                 `protobuf:"varint,8,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	ModelUriCheckpointLoad     bool                   `protobuf:"varint,9,opt,name=model_uri_checkpoint_load,json=modelUriCheckpointLoad,proto3" json:"model_uri_checkpoint_load,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *NativeColdStartMemoryEstimate) Reset() {
	*x = NativeColdStartMemoryEstimate{}
	mi := &file_training_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeColdStartMemoryEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeColdStartMemoryEstimate) ProtoMessage() {}

func (x *NativeColdStartMemoryEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeColdStartMemoryEstimate.ProtoReflect.Descriptor instead.
func (*NativeColdStartMemoryEstimate) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{5}
}

func (x *NativeColdStartMemoryEstimate) GetParameterBytesFp32() uint64 {
	if x != nil {
		return x.ParameterBytesFp32
	}
	return 0
}

func (x *NativeColdStartMemoryEstimate) GetAdamStateBytesFp32() uint64 {
	if x != nil {
		return x.AdamStateBytesFp32
	}
	return 0
}

func (x *NativeColdStartMemoryEstimate) GetActivationScratchBytesHint() uint64 {
	if x != nil {
		return x.ActivationScratchBytesHint
	}
	return 0
}

func (x *NativeColdStartMemoryEstimate) GetFormulaSummary() string {
	if x != nil {
		return x.FormulaSummary
	}
	return ""
}

func (x *NativeColdStartMemoryEstimate) GetEffectiveDModel() uint32 {
	if x != nil {
		return x.EffectiveDModel
	}
	return 0
}

func (x *NativeColdStartMemoryEstimate) GetEffectiveIoDModel() uint32 {
	if x != nil {
		return x.EffectiveIoDModel
	}
	return 0
}

func (x *NativeColdStartMemoryEstimate) GetEffectiveNumTernaryBlocks() uint32 {
	if x != nil {
		return x.EffectiveNumTernaryBlocks
	}
	return 0
}

func (x *NativeColdStartMemoryEstimate) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *NativeColdStartMemoryEstimate) GetModelUriCheckpointLoad() bool {
	if x != nil {
		return x.ModelUriCheckpointLoad
	}
	return false
}

type StartTrainingResponse struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	Accepted       bool                           `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message        string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RunId          string                         `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	MemoryEstimate *NativeColdStartMemoryEstimate `protobuf:"bytes,4,opt,name=memory_estimate,json=memoryEstimate,proto3" json:"memory_estimate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartTrainingResponse) Reset() {
	*x = StartTrainingResponse{}
	mi := &file_training_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrainingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrainingResponse) ProtoMessage() {}

func (x *StartTrainingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrainingResponse.ProtoReflect.Descriptor instead.
func (*StartTrainingResponse) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{6}
}

func (x *StartTrainingResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StartTrainingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartTrainingResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartTrainingResponse) GetMemoryEstimate() *NativeColdStartMemoryEstimate {
	if x != nil {
		return x.MemoryEstimate
	}
	return nil
}

type StopTrainingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTrainingRequest) Reset() {
	*x = StopTrainingRequest{}
	mi := &file_training_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTrainingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTrainingRequest) ProtoMessage() {}

func (x *StopTrainingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTrainingRequest.ProtoReflect.Descriptor instead.
func (*StopTrainingRequest) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{7}
}

func (x *StopTrainingRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StopTrainingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTrainingResponse) Reset() {
	*x = StopTrainingResponse{}
	mi := &file_training_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTrainingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTrainingResponse) ProtoMessage() {}

func (x *StopTrainingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTrainingResponse.ProtoReflect.Descriptor instead.
func (*StopTrainingResponse) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{8}
}

func (x *StopTrainingResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StopTrainingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_training_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{9}
}

func (x *StatusRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	State         StatusResponse_EngineState `protobuf:"varint,1,opt,name=state,proto3,enum=qminiwasm.trainingrpc.StatusResponse_EngineState" json:"state,omitempty"`
	RunId         string                     `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Epoch         uint32                     `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Step          uint32                     `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	TrainLoss     float64                    `protobuf:"fixed64,5,opt,name=train_loss,json=trainLoss,proto3" json:"train_loss,omitempty"`
	ValLoss       float64                    `protobuf:"fixed64,6,opt,name=val_loss,json=valLoss,proto3" json:"val_loss,omitempty"`
	LearningRate  float64                    `protobuf:"fixed64,7,opt,name=learning_rate,json=learningRate,proto3" json:"learning_rate,omitempty"`
	Message       string                     `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_training_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetState() StatusResponse_EngineState {
	if x != nil {
		return x.State
	}
	return StatusResponse_ENGINE_STATE_UNSPECIFIED
}

func (x *StatusResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StatusResponse) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *StatusResponse) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *StatusResponse) GetTrainLoss() float64 {
	if x != nil {
		return x.TrainLoss
	}
	return 0
}

func (x *StatusResponse) GetValLoss() float64 {
	if x != nil {
		return x.ValLoss
	}
	return 0
}

func (x *StatusResponse) GetLearningRate() float64 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	IncludeDebug  bool                   `protobuf:"varint,2,opt,name=include_debug,json=includeDebug,proto3" json:"include_debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_training_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{11}
}

func (x *TelemetryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TelemetryRequest) GetIncludeDebug() bool {
	if x != nil {
		return x.IncludeDebug
	}
	return false
}

type TelemetryEvent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RunId                string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	UnixMs               uint64                 `protobuf:"varint,2,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	Epoch                uint32                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Step                 uint32                 `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	TrainLoss            float64                `protobuf:"fixed64,5,opt,name=train_loss,json=trainLoss,proto3" json:"train_loss,omitempty"`
	ValLoss              float64                `protobuf:"fixed64,6,opt,name=val_loss,json=valLoss,proto3" json:"val_loss,omitempty"`
	LearningRate         float64                `protobuf:"fixed64,7,opt,name=learning_rate,json=learningRate,proto3" json:"learning_rate,omitempty"`
	SamplesPerSecond     float64                `protobuf:"fixed64,8,opt,name=samples_per_second,json=samplesPerSecond,proto3" json:"samples_per_second,omitempty"`
	SamplerQueueDepth    uint32                 `protobuf:"varint,9,opt,name=sampler_queue_depth,json=samplerQueueDepth,proto3" json:"sampler_queue_depth,omitempty"`
	PrefetchQueueDepth   uint32                 `protobuf:"varint,10,opt,name=prefetch_queue_depth,json=prefetchQueueDepth,proto3" json:"prefetch_queue_depth,omitempty"`
	ComputeQueueDepth    uint32                 `protobuf:"varint,11,opt,name=compute_queue_depth,json=computeQueueDepth,proto3" json:"compute_queue_depth,omitempty"`
	TaxonomyTier         string                 `protobuf:"bytes,12,opt,name=taxonomy_tier,json=taxonomyTier,proto3" json:"taxonomy_tier,omitempty"`
	PrecisionMode        string                 `protobuf:"bytes,13,opt,name=precision_mode,json=precisionMode,proto3" json:"precision_mode,omitempty"`
	Stage                string                 `protobuf:"bytes,14,opt,name=stage,proto3" json:"stage,omitempty"`
	EventType            string                 `protobuf:"bytes,15,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Message              string                 `protobuf:"bytes,16,opt,name=message,proto3" json:"message,omitempty"`
	GraphId              string                 `protobuf:"bytes,17,opt,name=graph_id,json=graphId,proto3" json:"graph_id,omitempty"`
	NodeId               string                 `protobuf:"bytes,18,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EnclaveState         string                 `protobuf:"bytes,19,opt,name=enclave_state,json=enclaveState,proto3" json:"enclave_state,omitempty"`
	AttestationState     string                 `protobuf:"bytes,20,opt,name=attestation_state,json=attestationState,proto3" json:"attestation_state,omitempty"`
	DecoherenceScore     float64                `protobuf:"fixed64,21,opt,name=decoherence_score,json=decoherenceScore,proto3" json:"decoherence_score,omitempty"`
	EpochWallS           float64                `protobuf:"fixed64,22,opt,name=epoch_wall_s,json=epochWallS,proto3" json:"epoch_wall_s,omitempty"`
	EpochBatchCount      uint32                 `protobuf:"varint,23,opt,name=epoch_batch_count,json=epochBatchCount,proto3" json:"epoch_batch_count,omitempty"`
	EpochSampleCount     uint64                 `protobuf:"varint,24,opt,name=epoch_sample_count,json=epochSampleCount,proto3" json:"epoch_sample_count,omitempty"`
	EpochMeanSamplesPerS float64                `protobuf:"fixed64,25,opt,name=epoch_mean_samples_per_s,json=epochMeanSamplesPerS,proto3" json:"epoch_mean_samples_per_s,omitempty"`
	HostRssMib           float64                `protobuf:"fixed64,26,opt,name=host_rss_mib,json=hostRssMib,proto3" json:"host_rss_mib,omitempty"`
	EstimatedTpemMib     float64                `protobuf:"fixed64,27,opt,name=estimated_tpem_mib,json=estimatedTpemMib,proto3" json:"estimated_tpem_mib,omitempty"`
	TierCapMib           float64                `protobuf:"fixed64,28,opt,name=tier_cap_mib,json=tierCapMib,proto3" json:"tier_cap_mib,omitempty"`
	// Unified Training Matrix: active phase name from TOML (e.g. sft, mopd).
	TrainingPhase string `protobuf:"bytes,29,opt,name=training_phase,json=trainingPhase,proto3" json:"training_phase,omitempty"`
	// Effective cascade policy for this segment: grpo or cispo (empty if N/A).
	CascadePolicyOptimizer string `protobuf:"bytes,30,opt,name=cascade_policy_optimizer,json=cascadePolicyOptimizer,proto3" json:"cascade_policy_optimizer,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_training_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_training_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_training_engine_proto_rawDescGZIP(), []int{12}
}

func (x *TelemetryEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TelemetryEvent) GetUnixMs() uint64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

func (x *TelemetryEvent) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TelemetryEvent) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *TelemetryEvent) GetTrainLoss() float64 {
	if x != nil {
		return x.TrainLoss
	}
	return 0
}

func (x *TelemetryEvent) GetValLoss() float64 {
	if x != nil {
		return x.ValLoss
	}
	return 0
}

func (x *TelemetryEvent) GetLearningRate() float64 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

func (x *TelemetryEvent) GetSamplesPerSecond() float64 {
	if x != nil {
		return x.SamplesPerSecond
	}
	return 0
}

func (x *TelemetryEvent) GetSamplerQueueDepth() uint32 {
	if x != nil {
		return x.SamplerQueueDepth
	}
	return 0
}

func (x *TelemetryEvent) GetPrefetchQueueDepth() uint32 {
	if x != nil {
		return x.PrefetchQueueDepth
	}
	return 0
}

func (x *TelemetryEvent) GetComputeQueueDepth() uint32 {
	if x != nil {
		return x.ComputeQueueDepth
	}
	return 0
}

func (x *TelemetryEvent) GetTaxonomyTier() string {
	if x != nil {
		return x.TaxonomyTier
	}
	return ""
}

func (x *TelemetryEvent) GetPrecisionMode() string {
	if x != nil {
		return x.PrecisionMode
	}
	return ""
}

func (x *TelemetryEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *TelemetryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TelemetryEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TelemetryEvent) GetGraphId() string {
	if x != nil {
		return x.GraphId
	}
	return ""
}

func (x *TelemetryEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetryEvent) GetEnclaveState() string {
	if x != nil {
		return x.EnclaveState
	}
	return ""
}

func (x *TelemetryEvent) GetAttestationState() string {
	if x != nil {
		return x.AttestationState
	}
	return ""
}

func (x *TelemetryEvent) GetDecoherenceScore() float64 {
	if x != nil {
		return x.DecoherenceScore
	}
	return 0
}

func (x *TelemetryEvent) GetEpochWallS() float64 {
	if x != nil {
		return x.EpochWallS
	}
	return 0
}

func (x *TelemetryEvent) GetEpochBatchCount() uint32 {
	if x != nil {
		return x.EpochBatchCount
	}
	return 0
}

func (x *TelemetryEvent) GetEpochSampleCount() uint64 {
	if x != nil {
		return x.EpochSampleCount
	}
	return 0
}

func (x *TelemetryEvent) GetEpochMeanSamplesPerS() float64 {
	if x != nil {
		return x.EpochMeanSamplesPerS
	}
	return 0
}

func (x *TelemetryEvent) GetHostRssMib() float64 {
	if x != nil {
		return x.HostRssMib
	}
	return 0
}

func (x *TelemetryEvent) GetEstimatedTpemMib() float64 {
	if x != nil {
		return x.EstimatedTpemMib
	}
	return 0
}

func (x *TelemetryEvent) GetTierCapMib() float64 {
	if x != nil {
		return x.TierCapMib
	}
	return 0
}

func (x *TelemetryEvent) GetTrainingPhase() string {
	if x != nil {
		return x.TrainingPhase
	}
	return ""
}

func (x *TelemetryEvent) GetCascadePolicyOptimizer() string {
	if x != nil {
		return x.CascadePolicyOptimizer
	}
	return ""
}

var File_training_engine_proto protoreflect.FileDescriptor

const file_training_engine_proto_rawDesc = "" +
	"\n" +
	"\x15training_engine.proto\x12\x15qminiwasm.trainingrpc\"\xd4\x01\n" +
	"\x0fHfDatasetParams\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\x12\x1f\n" +
	"\vconfig_name\x18\x02 \x01(\tR\n" +
	"configName\x12\x14\n" +
	"\x05split\x18\x03 \x01(\tR\x05split\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\tR\brevision\x12\x1f\n" +
	"\vnum_samples\x18\x05 \x01(\rR\n" +
	"numSamples\x12.\n" +
	"\x13mesh_blend_fraction\x18\x06 \x01(\x01R\x11meshBlendFraction\"\xa1\x04\n" +
	"\x1bCascadeCurriculumLoopParams\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12&\n" +
	"\x0fmax_heal_rounds\x18\x02 \x01(\rR\rmaxHealRounds\x126\n" +
	"\x17teacher_checkpoint_path\x18\x03 \x01(\tR\x15teacherCheckpointPath\x12(\n" +
	"\x10ptqtp_num_planes\x18\x04 \x01(\rR\x0eptqtpNumPlanes\x12-\n" +
	"\x13gate_target_val_mse\x18\x05 \x01(\x01R\x10gateTargetValMse\x12)\n" +
	"\x11gate_max_tpem_mib\x18\x06 \x01(\x01R\x0egateMaxTpemMib\x12.\n" +
	"\x13run_taxonomy_linter\x18\a \x01(\bR\x11runTaxonomyLinter\x127\n" +
	"\x18heal_learning_rate_scale\x18\b \x01(\x01R\x15healLearningRateScale\x124\n" +
	"\x16teacher_epoch_fraction\x18\t \x01(\x01R\x14teacherEpochFraction\x121\n" +
	"\x15heal_epochs_per_round\x18\n" +
	" \x01(\rR\x12healEpochsPerRound\x122\n" +
	"\x15max_curriculum_cycles\x18\v \x01(\rR\x13maxCurriculumCycles\"\xe2\x04\n" +
	"\x13TrainingPhaseParams\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06epochs\x18\x02 \x01(\rR\x06epochs\x12\x1e\n" +
	"\n" +
	"supervised\x18\x03 \x01(\bR\n" +
	"supervised\x12\x1d\n" +
	"\n" +
	"cascade_rl\x18\x04 \x01(\bR\tcascadeRl\x122\n" +
	"\x15freeze_model_backbone\x18\x05 \x01(\bR\x13freezeModelBackbone\x12\x1f\n" +
	"\vrouter_only\x18\x06 \x01(\bR\n" +
	"routerOnly\x128\n" +
	"\x18cascade_policy_optimizer\x18\a \x01(\tR\x16cascadePolicyOptimizer\x121\n" +
	"\x12cispo_clip_epsilon\x18\b \x01(\x01H\x00R\x10cispoClipEpsilon\x88\x01\x01\x123\n" +
	"\x13cascade_mopd_lambda\x18\t \x01(\x01H\x01R\x11cascadeMopdLambda\x88\x01\x01\x12.\n" +
	"\x10tequila_deadzone\x18\n" +
	" \x01(\x01H\x02R\x0ftequilaDeadzone\x88\x01\x01\x124\n" +
	"\x16freeze_ternary_experts\x18\v \x01(\bR\x14freezeTernaryExperts\x12?\n" +
	"\x1cmopd_teacher_checkpoint_path\x18\f \x01(\tR\x19mopdTeacherCheckpointPathB\x15\n" +
	"\x13_cispo_clip_epsilonB\x16\n" +
	"\x14_cascade_mopd_lambdaB\x13\n" +
	"\x11_tequila_deadzone\"\x88\n" +
	"\n" +
	"\x0eTrainingConfig\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vdataset_uri\x18\x02 \x01(\tR\n" +
	"datasetUri\x12\x1b\n" +
	"\tmodel_uri\x18\x03 \x01(\tR\bmodelUri\x12\x16\n" +
	"\x06epochs\x18\x04 \x01(\rR\x06epochs\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x05 \x01(\rR\tbatchSize\x12(\n" +
	"\x10micro_batch_size\x18\x06 \x01(\rR\x0emicroBatchSize\x12%\n" +
	"\x0eprefetch_depth\x18\a \x01(\rR\rprefetchDepth\x12#\n" +
	"\rcompute_slots\x18\b \x01(\rR\fcomputeSlots\x12%\n" +
	"\x0eworker_threads\x18\t \x01(\rR\rworkerThreads\x12#\n" +
	"\rlearning_rate\x18\n" +
	" \x01(\x01R\flearningRate\x12\x12\n" +
	"\x04seed\x18\v \x01(\x04R\x04seed\x12#\n" +
	"\rtaxonomy_tier\x18\f \x01(\tR\ftaxonomyTier\x12)\n" +
	"\x10precision_policy\x18\r \x01(\tR\x0fprecisionPolicy\x120\n" +
	"\x14checkpoint_save_path\x18\x0e \x01(\tR\x12checkpointSavePath\x120\n" +
	"\x14checkpoint_best_path\x18\x0f \x01(\tR\x12checkpointBestPath\x124\n" +
	"\x16checkpoint_latest_path\x18\x10 \x01(\tR\x14checkpointLatestPath\x12\x17\n" +
	"\ad_model\x18\x11 \x01(\rR\x06dModel\x12\x1c\n" +
	"\n" +
	"io_d_model\x18\x12 \x01(\rR\bioDModel\x12,\n" +
	"\x12num_ternary_blocks\x18\x13 \x01(\rR\x10numTernaryBlocks\x126\n" +
	"\x02hf\x18\x14 \x01(\v2&.qminiwasm.trainingrpc.HfDatasetParamsR\x02hf\x12U\n" +
	"\fcascade_loop\x18\x15 \x01(\v22.qminiwasm.trainingrpc.CascadeCurriculumLoopParamsR\vcascadeLoop\x123\n" +
	"\x16use_native_engine_only\x18\x16 \x01(\bR\x13useNativeEngineOnly\x12S\n" +
	"\x0ftraining_phases\x18\x17 \x03(\v2*.qminiwasm.trainingrpc.TrainingPhaseParamsR\x0etrainingPhases\x128\n" +
	"\x18cascade_policy_optimizer\x18\x18 \x01(\tR\x16cascadePolicyOptimizer\x12,\n" +
	"\x12cispo_clip_epsilon\x18\x19 \x01(\x01R\x10cispoClipEpsilon\x12+\n" +
	"\x11attention_backend\x18\x1a \x01(\tR\x10attentionBackend\x121\n" +
	"\x15cascade_rl_group_size\x18\x1b \x01(\rR\x12cascadeRlGroupSize\x12/\n" +
	"\x14native_bloch_seq_len\x18\x1c \x01(\rR\x11nativeBlochSeqLen\x123\n" +
	"\x16native_bloch_num_heads\x18\x1d \x01(\rR\x13nativeBlochNumHeads\"U\n" +
	"\x14StartTrainingRequest\x12=\n" +
	"\x06config\x18\x01 \x01(\v2%.qminiwasm.trainingrpc.TrainingConfigR\x06config\"\xe8\x03\n" +
	"\x1dNativeColdStartMemoryEstimate\x120\n" +
	"\x14parameter_bytes_fp32\x18\x01 \x01(\x04R\x12parameterBytesFp32\x121\n" +
	"\x15adam_state_bytes_fp32\x18\x02 \x01(\x04R\x12adamStateBytesFp32\x12A\n" +
	"\x1dactivation_scratch_bytes_hint\x18\x03 \x01(\x04R\x1aactivationScratchBytesHint\x12'\n" +
	"\x0fformula_summary\x18\x04 \x01(\tR\x0eformulaSummary\x12*\n" +
	"\x11effective_d_model\x18\x05 \x01(\rR\x0feffectiveDModel\x12/\n" +
	"\x14effective_io_d_model\x18\x06 \x01(\rR\x11effectiveIoDModel\x12?\n" +
	"\x1ceffective_num_ternary_blocks\x18\a \x01(\rR\x19effectiveNumTernaryBlocks\x12\x1d\n" +
	"\n" +
	"batch_size\x18\b \x01(\rR\tbatchSize\x129\n" +
	"\x19model_uri_checkpoint_load\x18\t \x01(\bR\x16modelUriCheckpointLoad\"\xc3\x01\n" +
	"\x15StartTrainingResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12]\n" +
	"\x0fmemory_estimate\x18\x04 \x01(\v24.qminiwasm.trainingrpc.NativeColdStartMemoryEstimateR\x0ememoryEstimate\",\n" +
	"\x13StopTrainingRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"L\n" +
	"\x14StopTrainingResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\rStatusRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xdb\x03\n" +
	"\x0eStatusResponse\x12G\n" +
	"\x05state\x18\x01 \x01(\x0e21.qminiwasm.trainingrpc.StatusResponse.EngineStateR\x05state\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x12\x12\n" +
	"\x04step\x18\x04 \x01(\rR\x04step\x12\x1d\n" +
	"\n" +
	"train_loss\x18\x05 \x01(\x01R\ttrainLoss\x12\x19\n" +
	"\bval_loss\x18\x06 \x01(\x01R\avalLoss\x12#\n" +
	"\rlearning_rate\x18\a \x01(\x01R\flearningRate\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\"\xc5\x01\n" +
	"\vEngineState\x12\x1c\n" +
	"\x18ENGINE_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ENGINE_STATE_IDLE\x10\x01\x12\x19\n" +
	"\x15ENGINE_STATE_STARTING\x10\x02\x12\x18\n" +
	"\x14ENGINE_STATE_RUNNING\x10\x03\x12\x19\n" +
	"\x15ENGINE_STATE_STOPPING\x10\x04\x12\x18\n" +
	"\x14ENGINE_STATE_STOPPED\x10\x05\x12\x17\n" +
	"\x13ENGINE_STATE_FAILED\x10\x06\"N\n" +
	"\x10TelemetryRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rinclude_debug\x18\x02 \x01(\bR\fincludeDebug\"\xde\b\n" +
	"\x0eTelemetryEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\aunix_ms\x18\x02 \x01(\x04R\x06unixMs\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x12\x12\n" +
	"\x04step\x18\x04 \x01(\rR\x04step\x12\x1d\n" +
	"\n" +
	"train_loss\x18\x05 \x01(\x01R\ttrainLoss\x12\x19\n" +
	"\bval_loss\x18\x06 \x01(\x01R\avalLoss\x12#\n" +
	"\rlearning_rate\x18\a \x01(\x01R\flearningRate\x12,\n" +
	"\x12samples_per_second\x18\b \x01(\x01R\x10samplesPerSecond\x12.\n" +
	"\x13sampler_queue_depth\x18\t \x01(\rR\x11samplerQueueDepth\x120\n" +
	"\x14prefetch_queue_depth\x18\n" +
	" \x01(\rR\x12prefetchQueueDepth\x12.\n" +
	"\x13compute_queue_depth\x18\v \x01(\rR\x11computeQueueDepth\x12#\n" +
	"\rtaxonomy_tier\x18\f \x01(\tR\ftaxonomyTier\x12%\n" +
	"\x0eprecision_mode\x18\r \x01(\tR\rprecisionMode\x12\x14\n" +
	"\x05stage\x18\x0e \x01(\tR\x05stage\x12\x1d\n" +
	"\n" +
	"event_type\x18\x0f \x01(\tR\teventType\x12\x18\n" +
	"\amessage\x18\x10 \x01(\tR\amessage\x12\x19\n" +
	"\bgraph_id\x18\x11 \x01(\tR\agraphId\x12\x17\n" +
	"\anode_id\x18\x12 \x01(\tR\x06nodeId\x12#\n" +
	"\renclave_state\x18\x13 \x01(\tR\fenclaveState\x12+\n" +
	"\x11attestation_state\x18\x14 \x01(\tR\x10attestationState\x12+\n" +
	"\x11decoherence_score\x18\x15 \x01(\x01R\x10decoherenceScore\x12 \n" +
	"\fepoch_wall_s\x18\x16 \x01(\x01R\n" +
	"epochWallS\x12*\n" +
	"\x11epoch_batch_count\x18\x17 \x01(\rR\x0fepochBatchCount\x12,\n" +
	"\x12epoch_sample_count\x18\x18 \x01(\x04R\x10epochSampleCount\x126\n" +
	"\x18epoch_mean_samples_per_s\x18\x19 \x01(\x01R\x14epochMeanSamplesPerS\x12 \n" +
	"\fhost_rss_mib\x18\x1a \x01(\x01R\n" +
	"hostRssMib\x12,\n" +
	"\x12estimated_tpem_mib\x18\x1b \x01(\x01R\x10estimatedTpemMib\x12 \n" +
	"\ftier_cap_mib\x18\x1c \x01(\x01R\n" +
	"tierCapMib\x12%\n" +
	"\x0etraining_phase\x18\x1d \x01(\tR\rtrainingPhase\x128\n" +
	"\x18cascade_policy_optimizer\x18\x1e \x01(\tR\x16cascadePolicyOptimizer2\xab\x03\n" +
	"\x15TrainingEngineService\x12j\n" +
	"\rStartTraining\x12+.qminiwasm.trainingrpc.StartTrainingRequest\x1a,.qminiwasm.trainingrpc.StartTrainingResponse\x12g\n" +
	"\fStopTraining\x12*.qminiwasm.trainingrpc.StopTrainingRequest\x1a+.qminiwasm.trainingrpc.StopTrainingResponse\x12X\n" +
	"\tGetStatus\x12$.qminiwasm.trainingrpc.StatusRequest\x1a%.qminiwasm.trainingrpc.StatusResponse\x12c\n" +
	"\x0fStreamTelemetry\x12'.qminiwasm.trainingrpc.TelemetryRequest\x1a%.qminiwasm.trainingrpc.TelemetryEvent0\x01BTZRgithub.com/kennetholsenatm-gif/qminiwasm-core/training-wui/trainingrpc;trainingrpcb\x06proto3"

var (
	file_training_engine_proto_rawDescOnce sync.Once
	file_training_engine_proto_rawDescData []byte
)

func file_training_engine_proto_rawDescGZIP() []byte {
	file_training_engine_proto_rawDescOnce.Do(func() {
		file_training_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_training_engine_proto_rawDesc), len(file_training_engine_proto_rawDesc)))
	})
	return file_training_engine_proto_rawDescData
}

var file_training_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_training_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_training_engine_proto_goTypes = []any{
	(StatusResponse_EngineState)(0),       // 0: qminiwasm.trainingrpc.StatusResponse.EngineState
	(*HfDatasetParams)(nil),               // 1: qminiwasm.trainingrpc.HfDatasetParams
	(*CascadeCurriculumLoopParams)(nil),   // 2: qminiwasm.trainingrpc.CascadeCurriculumLoopParams
	(*TrainingPhaseParams)(nil),           // 3: qminiwasm.trainingrpc.TrainingPhaseParams
	(*TrainingConfig)(nil),                // 4: qminiwasm.trainingrpc.TrainingConfig
	(*StartTrainingRequest)(nil),          // 5: qminiwasm.trainingrpc.StartTrainingRequest
	(*NativeColdStartMemoryEstimate)(nil), // 6: qminiwasm.trainingrpc.NativeColdStartMemoryEstimate
	(*StartTrainingResponse)(nil),         // 7: qminiwasm.trainingrpc.StartTrainingResponse
	(*StopTrainingRequest)(nil),           // 8: qminiwasm.trainingrpc.StopTrainingRequest
	(*StopTrainingResponse)(nil),          // 9: qminiwasm.trainingrpc.StopTrainingResponse
	(*StatusRequest)(nil),                 // 10: qminiwasm.trainingrpc.StatusRequest
	(*StatusResponse)(nil),                // 11: qminiwasm.trainingrpc.StatusResponse
	(*TelemetryRequest)(nil),              // 12: qminiwasm.trainingrpc.TelemetryRequest
	(*TelemetryEvent)(nil),                // 13: qminiwasm.trainingrpc.TelemetryEvent
}
var file_training_engine_proto_depIdxs = []int32{
	1,  // 0: qminiwasm.trainingrpc.TrainingConfig.hf:type_name -> qminiwasm.trainingrpc.HfDatasetParams
	2,  // 1: qminiwasm.trainingrpc.TrainingConfig.cascade_loop:type_name -> qminiwasm.trainingrpc.CascadeCurriculumLoopParams
	3,  // 2: qminiwasm.trainingrpc.TrainingConfig.training_phases:type_name -> qminiwasm.trainingrpc.TrainingPhaseParams
	4,  // 3: qminiwasm.trainingrpc.StartTrainingRequest.config:type_name -> qminiwasm.trainingrpc.TrainingConfig
	6,  // 4: qminiwasm.trainingrpc.StartTrainingResponse.memory_estimate:type_name -> qminiwasm.trainingrpc.NativeColdStartMemoryEstimate
	0,  // 5: qminiwasm.trainingrpc.StatusResponse.state:type_name -> qminiwasm.trainingrpc.StatusResponse.EngineState
	5,  // 6: qminiwasm.trainingrpc.TrainingEngineService.StartTraining:input_type -> qminiwasm.trainingrpc.StartTrainingRequest
	8,  // 7: qminiwasm.trainingrpc.TrainingEngineService.StopTraining:input_type -> qminiwasm.trainingrpc.StopTrainingRequest
	10, // 8: qminiwasm.trainingrpc.TrainingEngineService.GetStatus:input_type -> qminiwasm.trainingrpc.StatusRequest
	12, // 9: qminiwasm.trainingrpc.TrainingEngineService.StreamTelemetry:input_type -> qminiwasm.trainingrpc.TelemetryRequest
	7,  // 10: qminiwasm.trainingrpc.TrainingEngineService.StartTraining:output_type -> qminiwasm.trainingrpc.StartTrainingResponse
	9,  // 11: qminiwasm.trainingrpc.TrainingEngineService.StopTraining:output_type -> qminiwasm.trainingrpc.StopTrainingResponse
	11, // 12: qminiwasm.trainingrpc.TrainingEngineService.GetStatus:output_type -> qminiwasm.trainingrpc.StatusResponse
	13, // 13: qminiwasm.trainingrpc.TrainingEngineService.StreamTelemetry:output_type -> qminiwasm.trainingrpc.TelemetryEvent
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_training_engine_proto_init() }
func file_training_engine_proto_init() {
	if File_training_engine_proto != nil {
		return
	}
	file_training_engine_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_training_engine_proto_rawDesc), len(file_training_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_training_engine_proto_goTypes,
		DependencyIndexes: file_training_engine_proto_depIdxs,
		EnumInfos:         file_training_engine_proto_enumTypes,
		MessageInfos:      file_training_engine_proto_msgTypes,
	}.Build()
	File_training_engine_proto = out.File
	file_training_engine_proto_goTypes = nil
	file_training_engine_proto_depIdxs = nil
}
