// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.1
// source: training_engine.proto

package trainingrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrainingEngineService_StartTraining_FullMethodName   = "/qminiwasm.trainingrpc.TrainingEngineService/StartTraining"
	TrainingEngineService_StopTraining_FullMethodName    = "/qminiwasm.trainingrpc.TrainingEngineService/StopTraining"
	TrainingEngineService_GetStatus_FullMethodName       = "/qminiwasm.trainingrpc.TrainingEngineService/GetStatus"
	TrainingEngineService_StreamTelemetry_FullMethodName = "/qminiwasm.trainingrpc.TrainingEngineService/StreamTelemetry"
)

// TrainingEngineServiceClient is the client API for TrainingEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainingEngineServiceClient interface {
	StartTraining(ctx context.Context, in *StartTrainingRequest, opts ...grpc.CallOption) (*StartTrainingResponse, error)
	StopTraining(ctx context.Context, in *StopTrainingRequest, opts ...grpc.CallOption) (*StopTrainingResponse, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	StreamTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryEvent], error)
}

type trainingEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainingEngineServiceClient(cc grpc.ClientConnInterface) TrainingEngineServiceClient {
	return &trainingEngineServiceClient{cc}
}

func (c *trainingEngineServiceClient) StartTraining(ctx context.Context, in *StartTrainingRequest, opts ...grpc.CallOption) (*StartTrainingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTrainingResponse)
	err := c.cc.Invoke(ctx, TrainingEngineService_StartTraining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingEngineServiceClient) StopTraining(ctx context.Context, in *StopTrainingRequest, opts ...grpc.CallOption) (*StopTrainingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTrainingResponse)
	err := c.cc.Invoke(ctx, TrainingEngineService_StopTraining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingEngineServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TrainingEngineService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainingEngineServiceClient) StreamTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrainingEngineService_ServiceDesc.Streams[0], TrainingEngineService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryRequest, TelemetryEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrainingEngineService_StreamTelemetryClient = grpc.ServerStreamingClient[TelemetryEvent]

// TrainingEngineServiceServer is the server API for TrainingEngineService service.
// All implementations must embed UnimplementedTrainingEngineServiceServer
// for forward compatibility.
type TrainingEngineServiceServer interface {
	StartTraining(context.Context, *StartTrainingRequest) (*StartTrainingResponse, error)
	StopTraining(context.Context, *StopTrainingRequest) (*StopTrainingResponse, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	StreamTelemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetryEvent]) error
	mustEmbedUnimplementedTrainingEngineServiceServer()
}

// UnimplementedTrainingEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainingEngineServiceServer struct{}

func (UnimplementedTrainingEngineServiceServer) StartTraining(context.Context, *StartTrainingRequest) (*StartTrainingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTraining not implemented")
}
func (UnimplementedTrainingEngineServiceServer) StopTraining(context.Context, *StopTrainingRequest) (*StopTrainingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTraining not implemented")
}
func (UnimplementedTrainingEngineServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTrainingEngineServiceServer) StreamTelemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetryEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedTrainingEngineServiceServer) mustEmbedUnimplementedTrainingEngineServiceServer() {}
func (UnimplementedTrainingEngineServiceServer) testEmbeddedByValue()                               {}

// UnsafeTrainingEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainingEngineServiceServer will
// result in compilation errors.
type UnsafeTrainingEngineServiceServer interface {
	mustEmbedUnimplementedTrainingEngineServiceServer()
}

func RegisterTrainingEngineServiceServer(s grpc.ServiceRegistrar, srv TrainingEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedTrainingEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrainingEngineService_ServiceDesc, srv)
}

func _TrainingEngineService_StartTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingEngineServiceServer).StartTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingEngineService_StartTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingEngineServiceServer).StartTraining(ctx, req.(*StartTrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingEngineService_StopTraining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTrainingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingEngineServiceServer).StopTraining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingEngineService_StopTraining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingEngineServiceServer).StopTraining(ctx, req.(*StopTrainingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingEngineService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainingEngineServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrainingEngineService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainingEngineServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrainingEngineService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrainingEngineServiceServer).StreamTelemetry(m, &grpc.GenericServerStream[TelemetryRequest, TelemetryEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrainingEngineService_StreamTelemetryServer = grpc.ServerStreamingServer[TelemetryEvent]

// TrainingEngineService_ServiceDesc is the grpc.ServiceDesc for TrainingEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrainingEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qminiwasm.trainingrpc.TrainingEngineService",
	HandlerType: (*TrainingEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTraining",
			Handler:    _TrainingEngineService_StartTraining_Handler,
		},
		{
			MethodName: "StopTraining",
			Handler:    _TrainingEngineService_StopTraining_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _TrainingEngineService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _TrainingEngineService_StreamTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "training_engine.proto",
}
