#!/usr/bin/env python3
"""
Research Pipeline Report Generator

Generates a comprehensive report of the research-to-production pipeline execution.
"""

import argparse
import json
from pathlib import Path
from datetime import datetime


def load_gap_report(gap_report_path: str) -> dict:
    """Load gap analysis report."""
    try:
        with open(gap_report_path, 'r') as f:
            return json.load(f)
    except:
        return {}


def count_prompts(prompts_dir: str) -> int:
    """Count generated prompt files."""
    try:
        prompts_path = Path(prompts_dir)
        if prompts_path.exists():
            return len(list(prompts_path.glob('*.md')))
    except:
        pass
    return 0


def generate_report(gap_report: dict, prompts_count: int, config: dict) -> str:
    """Generate markdown report."""
    timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    gaps = gap_report.get('gaps', [])
    overall_coverage = gap_report.get('overall_coverage', 0)
    
    report = f"""# Research-to-Production Pipeline Report

**Generated:** {timestamp}

## Summary

- **Overall Research Coverage:** {overall_coverage:.1%}
- **Research Gaps Identified:** {len(gaps)}
- **Deep Research Prompts Generated:** {prompts_count}

## Research Gaps

"""
    
    if gaps:
        report += "| Concept | Priority | Current Coverage |\n"
        report += "|---------|----------|------------------|\n"
        for gap in gaps:
            concept = gap.get('concept_name', 'Unknown')
            priority = gap.get('priority', 'medium')
            coverage = gap.get('current_coverage', 0)
            report += f"| {concept} | {priority.upper()} | {coverage:.1%} |\n"
    else:
        report += "No research gaps detected. All core concepts have adequate coverage.\n"
    
    report += f"""
## Concepts Coverage

"""
    
    coverage_data = gap_report.get('concepts_coverage', {})
    if coverage_data:
        report += "| Concept | Mentioned | Coverage Score |\n"
        report += "|---------|-----------|----------------|\n"
        for concept_key, concept_data in coverage_data.items():
            name = concept_data.get('name', concept_key)
            mentioned = "✓" if concept_data.get('mentioned', False) else "✗"
            score = concept_data.get('coverage_score', 0)
            report += f"| {name} | {mentioned} | {score:.1%} |\n"
    
    report += f"""
## Next Steps

1. **Human Review:** Review generated deep research prompts
2. **AI Agent Research:** Pass approved prompts to deep research AI agent
3. **Integration:** Incorporate research findings into framework
4. **Validation:** Test implementations against performance targets

## Pipeline Configuration

- **Research Alignment Config:** config/research-alignment.json
- **Core Concepts:** config/core-concepts.json
- **Research Documents:** docs/research/

---
*Report generated by the Research-to-Production Pipeline*
"""
    
    return report


def main():
    parser = argparse.ArgumentParser(description='Generate pipeline report')
    parser.add_argument('--gap-analysis', required=True, help='Gap analysis report')
    parser.add_argument('--prompts-dir', required=True, help='Generated prompts directory')
    parser.add_argument('--config', required=True, help='Research alignment config')
    parser.add_argument('--output', required=True, help='Output path for report')
    
    args = parser.parse_args()
    
    # Load data
    gap_report = load_gap_report(args.gap_analysis)
    prompts_count = count_prompts(args.prompts_dir)
    
    try:
        with open(args.config, 'r') as f:
            config = json.load(f)
    except:
        config = {}
    
    # Generate report
    report = generate_report(gap_report, prompts_count, config)
    
    # Write output
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"Pipeline report generated: {args.output}")
    
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main())