#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Move datasets, weights, and checkpoints outside git repository.
    
.DESCRIPTION
    This script moves large data files to an external directory (outside git)
    to keep the repository lean. Creates symlinks for backward compatibility.
    
    Default external location: C:\q_mini_data\
    
.EXAMPLE
    .\scripts\setup_external_data.ps1
    .\scripts\setup_external_data.ps1 -DataPath "D:\ML_Data\q_mini"
#>

param(
    [string]$DataPath = "C:\q_mini_data",
    [string]$RepoPath = $PSScriptRoot | Split-Path -Parent
)

$ErrorActionPreference = "Stop"

Write-Host "=== Q-MINI External Data Setup ===" -ForegroundColor Cyan
Write-Host "External data path: $DataPath"
Write-Host "Repository path: $RepoPath"
Write-Host ""

# Create external directory structure
$dirs = @(
    "$DataPath\datasets",
    "$DataPath\weights",
    "$DataPath\checkpoints",
    "$DataPath\logs"
)

foreach ($dir in $dirs) {
    if (!(Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "Created: $dir" -ForegroundColor Green
    }
}

# Function to move files with progress
function Move-DataFiles {
    param($Source, $Destination, $Pattern, $Description)
    
    $files = Get-ChildItem -Path $Source -Filter $Pattern -ErrorAction SilentlyContinue
    if (!$files) { return }
    
    Write-Host "Moving $Description..." -ForegroundColor Yellow
    $count = 0
    $total = $files.Count
    $movedSize = 0
    
    foreach ($file in $files) {
        $destPath = Join-Path $Destination $file.Name
        if (Test-Path $destPath) {
            Write-Host "  Skipping $($file.Name) (already exists)" -ForegroundColor Gray
            continue
        }
        
        Move-Item -Path $file.FullName -Destination $destPath -Force
        $movedSize += $file.Length
        $count++
        
        if ($count % 100 -eq 0 -or $count -eq $total) {
            Write-Host "  Progress: $count/$total files" -ForegroundColor Gray
        }
    }
    
    $sizeMB = [math]::Round($movedSize / 1MB, 2)
    Write-Host "  Moved $count files ($sizeMB MB)" -ForegroundColor Green
    return $movedSize
}

# Move datasets
$totalMoved = 0
$totalMoved += Move-DataFiles -Source "$RepoPath\datasets" -Destination "$DataPath\datasets" -Pattern "book_pg_*.txt" -Description "Gutenberg books"
$totalMoved += Move-DataFiles -Source "$RepoPath\datasets" -Destination "$DataPath\datasets" -Pattern "*.jsonl" -Description "JSONL datasets"
$totalMoved += Move-DataFiles -Source "$RepoPath\datasets" -Destination "$DataPath\datasets" -Pattern "*.t3b" -Description "T3B binary datasets"

# Move checkpoints (if any in repo root)
$totalMoved += Move-DataFiles -Source "$RepoPath" -Destination "$DataPath\checkpoints" -Pattern "*.weights" -Description "Model weights"

# Calculate total
$totalMB = [math]::Round($totalMoved / 1MB, 2)
Write-Host ""
Write-Host "Total moved: $totalMB MB" -ForegroundColor Cyan

# Create/update symlink for datasets (optional, requires admin)
$datasetLink = "$RepoPath\datasets\external"
if (!(Test-Path $datasetLink) -and ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    New-Item -ItemType SymbolicLink -Path $datasetLink -Target "$DataPath\datasets" | Out-Null
    Write-Host "Created symlink: datasets\external -> $DataPath\datasets" -ForegroundColor Green
}

# Generate config update
Write-Host ""
Write-Host "=== Update your training_config.toml ===" -ForegroundColor Cyan
Write-Host "[paths]"
Write-Host "dataset_dir = '$DataPath\datasets'"
Write-Host "checkpoint_dir = '$DataPath\checkpoints'"
Write-Host "weights_dir = '$DataPath\weights'"
Write-Host "logs_dir = '$DataPath\logs'"
Write-Host ""

# Create a local config override file
$localConfig = @"
# Local data paths (auto-generated by setup_external_data.ps1)
# This file is git-ignored and overrides default paths

[dataset]
path = '$DataPath\datasets\seed_large_v2.t3b'
format = 't3b'

[paths]
dataset_dir = '$DataPath\datasets'
checkpoint_dir = '$DataPath\checkpoints'
weights_dir = '$DataPath\weights'
logs_dir = '$DataPath\logs'
"@

$localConfigPath = "$RepoPath\config\local_data_paths.toml"
$localConfig | Out-File -FilePath $localConfigPath -Encoding UTF8
Write-Host "Created local config: $localConfigPath" -ForegroundColor Green
Write-Host "(This file is automatically git-ignored)" -ForegroundColor Gray

Write-Host ""
Write-Host "Setup complete! Large data files are now outside git." -ForegroundColor Green
