package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// TestAgent generates and runs tests
type TestAgent struct {
	Name           string
	SupportedLangs []string
	TestFrameworks map[string]string
	TestResults    map[string]*TestResult
}

// TestResult represents test execution results
type TestResult struct {
	TestFile   string     `json:"test_file"`
	Language   string     `json:"language"`
	TotalTests int        `json:"total_tests"`
	Passed     int        `json:"passed"`
	Failed     int        `json:"failed"`
	Skipped    int        `json:"skipped"`
	Duration   float64    `json:"duration_seconds"`
	Tests      []TestCase `json:"tests"`
	Coverage   *Coverage  `json:"coverage,omitempty"`
	Timestamp  time.Time  `json:"timestamp"`
}

// TestCase represents a single test case
type TestCase struct {
	Name     string  `json:"name"`
	Status   string  `json:"status"`
	Duration float64 `json:"duration"`
	Message  string  `json:"message,omitempty"`
	Line     int     `json:"line"`
}

// Coverage represents code coverage metrics
type Coverage struct {
	LineCoverage     float64 `json:"line_coverage"`
	BranchCoverage   float64 `json:"branch_coverage"`
	FunctionCoverage float64 `json:"function_coverage"`
	UncoveredLines   []int   `json:"uncovered_lines"`
}

// TestConfig represents test configuration
type TestConfig struct {
	Language      string `json:"language"`
	TestFile      string `json:"test_file"`
	SourceFile    string `json:"source_file"`
	TestFramework string `json:"test_framework"`
	BuildCommand  string `json:"build_command"`
	RunCommand    string `json:"run_command"`
}

// NewTestAgent creates a new TestAgent
func NewTestAgent() *TestAgent {
	return &TestAgent{
		Name:           "TestAgent",
		SupportedLangs: []string{"C++", "Go", "R", "Python"},
		TestFrameworks: map[string]string{
			"C++":    "Catch2/gtest",
			"Go":     "testing",
			"R":      "testthat",
			"Python": "pytest",
		},
		TestResults: make(map[string]*TestResult),
	}
}

// GenerateTests generates test files for a source file
func (t *TestAgent) GenerateTests(sourceFile string, language string) (string, error) {
	content, err := os.ReadFile(sourceFile)
	if err != nil {
		return "", fmt.Errorf("failed to read source file: %w", err)
	}

	var testCode string
	switch language {
	case "C++":
		testCode = t.generateCPPTests(sourceFile, string(content))
	case "Go":
		testCode = t.generateGoTests(sourceFile, string(content))
	case "R":
		testCode = t.generateRTests(sourceFile, string(content))
	case "Python":
		testCode = t.generatePythonTests(sourceFile, string(content))
	default:
		return "", fmt.Errorf("unsupported language: %s", language)
	}

	return testCode, nil
}

// generateCPPTests generates C++ test code with meaningful test cases
func (t *TestAgent) generateCPPTests(sourceFile string, content string) string {
	testFile := strings.TrimSuffix(sourceFile, filepath.Ext(sourceFile)) + "_test.cpp"

	// Extract function names from source content
	functions := extractFunctionNames(content)

	// Generate actual test cases based on detected functions
	testCases := ""
	if len(functions) > 0 {
		for _, fn := range functions {
			testCases += fmt.Sprintf(`
TEST_CASE("%s basic operation", "[%s]") {
    // Arrange
    auto instance = create_%s_instance();
    REQUIRE(instance != nullptr);
    
    // Act & Assert
    auto result = instance->%s();
    REQUIRE(result.is_valid());
}
`, fn, fn, fn, fn)
		}
	} else {
		// Fallback to generic tests if no functions detected
		testCases = `TEST_CASE("Module loads correctly", "[sanity]") {
    REQUIRE(true); // Module loaded without crashing
}

TEST_CASE("Memory allocation works", "[memory]") {
    auto ptr = std::make_unique<int>(42);
    REQUIRE(ptr != nullptr);
    REQUIRE(*ptr == 42);
}

TEST_CASE("Basic arithmetic operations", "[math]") {
    REQUIRE(2 + 2 == 4);
    REQUIRE(10 - 5 == 5);
    REQUIRE(3 * 3 == 9);
}
`
	}

	return fmt.Sprintf(`// Generated Test File for %s
// Auto-generated by TestAgent with function analysis

#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include <memory>

#include "../%s"

// Forward declarations for test helpers
class TestFixture {
public:
    void setup() { /* Setup test environment */ }
    void teardown() { /* Cleanup test environment */ }
};

%s

TEST_CASE("Performance baseline", "[performance]") {
    BENCHMARK("Simple operation") {
        return 42 * 42;
    };
}
`, sourceFile, filepath.Base(sourceFile), testCases)

	_ = testFile // Test file name for reference
}

// generateGoTests generates Go test code with meaningful test cases
func (t *TestAgent) generateGoTests(sourceFile string, content string) string {
	// Extract function names from source
	functions := extractFunctionNames(content)

	// Generate actual test cases
	testCases := ""
	if len(functions) > 0 {
		for _, fn := range functions {
			testCases += fmt.Sprintf(`
func Test%sBasicOperation(t *testing.T) {
    // Arrange
    instance, err := New%s()
    if err != nil {
        t.Fatalf("Failed to create instance: %%v", err)
    }
    
    // Act
    result, err := instance.%s()
    
    // Assert
    if err != nil {
        t.Errorf("%s() returned error: %%v", err)
    }
    if result == nil {
        t.Error("%s() returned nil result")
    }
}

func Test%sErrorHandling(t *testing.T) {
    // Test error conditions
    instance := &%s{}
    _, err := instance.%sWithInvalidInput()
    if err == nil {
        t.Error("Expected error for invalid input, got nil")
    }
}
`, fn, fn, fn, fn, fn, fn, fn, fn)
		}
	} else {
		// Generic tests
		testCases = `func TestModuleLoads(t *testing.T) {
    // Verify module can be instantiated
    t.Log("Module loaded successfully")
}

func TestBasicArithmetic(t *testing.T) {
    if 2+2 != 4 {
        t.Error("Basic arithmetic failed")
    }
}
`
	}

	return fmt.Sprintf(`// Generated Test File for %s
// Auto-generated by TestAgent with function analysis

package main

import (
    "testing"
)

%s

func BenchmarkBasicOperation(b *testing.B) {
    for i := 0; i < b.N; i++ {
        _ = 42 * 42
    }
}
`, sourceFile, testCases)
}

// generateRTests generates R test code
func (t *TestAgent) generateRTests(sourceFile string, content string) string {
	return fmt.Sprintf(`# Generated Test File for %s
# Auto-generated by TestAgent

library(testthat)

test_that("Basic Functionality", {
  # TODO: Add test cases based on source file analysis
  expect_true(TRUE)
})

test_that("Edge Cases", {
  # TODO: Add edge case tests
  expect_true(TRUE)
})

test_that("Error Handling", {
  # TODO: Add error handling tests
  expect_error(stop("test error"))
})
`, sourceFile)
}

// generatePythonTests generates Python test code
func (t *TestAgent) generatePythonTests(sourceFile string, content string) string {
	return fmt.Sprintf(`# Generated Test File for %s
# Auto-generated by TestAgent

import pytest

def test_basic_functionality():
    """TODO: Add test cases based on source file analysis"""
    assert True

def test_edge_cases():
    """TODO: Add edge case tests"""
    assert True

def test_error_handling():
    """TODO: Add error handling tests"""
    with pytest.raises(Exception):
        raise Exception("test error")

@pytest.mark.parametrize("input,expected", [
    (1, 2),
    (2, 4),
    (3, 6),
])
def test_parametrized(input, expected):
    """TODO: Add parametrized tests"""
    assert input * 2 == expected
`, sourceFile)
}

// RunTests runs tests for a given file or directory
func (t *TestAgent) RunTests(testFile string, language string) (*TestResult, error) {
	result := &TestResult{
		TestFile:  testFile,
		Language:  language,
		Tests:     []TestCase{},
		Timestamp: time.Now(),
	}

	// Simulate test execution (in production, this would actually run tests)
	switch language {
	case "Go":
		t.simulateGoTests(result)
	case "C++":
		t.simulateCPPTests(result)
	case "R":
		t.simulateRTests(result)
	case "Python":
		t.simulatePythonTests(result)
	default:
		return nil, fmt.Errorf("unsupported language: %s", language)
	}

	// Calculate totals
	result.TotalTests = len(result.Tests)
	for _, test := range result.Tests {
		switch test.Status {
		case "passed":
			result.Passed++
		case "failed":
			result.Failed++
		case "skipped":
			result.Skipped++
		}
	}

	// Cache result
	t.TestResults[testFile] = result

	return result, nil
}

// simulateGoTests simulates Go test execution
func (t *TestAgent) simulateGoTests(result *TestResult) {
	result.Tests = []TestCase{
		{Name: "TestBasicFunctionality", Status: "passed", Duration: 0.001, Line: 10},
		{Name: "TestEdgeCases", Status: "passed", Duration: 0.002, Line: 15},
		{Name: "TestErrorHandling", Status: "passed", Duration: 0.001, Line: 20},
		{Name: "BenchmarkPerformance", Status: "skipped", Duration: 0, Line: 25, Message: "Benchmark skipped in normal test run"},
	}
	result.Duration = 0.004
	result.Coverage = &Coverage{
		LineCoverage:     85.0,
		BranchCoverage:   75.0,
		FunctionCoverage: 90.0,
		UncoveredLines:   []int{30, 31, 32},
	}
}

// simulateCPPTests simulates C++ test execution
func (t *TestAgent) simulateCPPTests(result *TestResult) {
	result.Tests = []TestCase{
		{Name: "Basic Functionality", Status: "passed", Duration: 0.002, Line: 10},
		{Name: "Edge Cases", Status: "passed", Duration: 0.003, Line: 15},
		{Name: "Error Handling", Status: "passed", Duration: 0.001, Line: 20},
		{Name: "Performance", Status: "passed", Duration: 0.005, Line: 25},
	}
	result.Duration = 0.011
	result.Coverage = &Coverage{
		LineCoverage:     80.0,
		BranchCoverage:   70.0,
		FunctionCoverage: 85.0,
		UncoveredLines:   []int{35, 36, 37, 38},
	}
}

// simulateRTests simulates R test execution
func (t *TestAgent) simulateRTests(result *TestResult) {
	result.Tests = []TestCase{
		{Name: "Basic Functionality", Status: "passed", Duration: 0.01, Line: 6},
		{Name: "Edge Cases", Status: "passed", Duration: 0.008, Line: 11},
		{Name: "Error Handling", Status: "passed", Duration: 0.005, Line: 16},
	}
	result.Duration = 0.023
	result.Coverage = &Coverage{
		LineCoverage:     78.0,
		BranchCoverage:   65.0,
		FunctionCoverage: 82.0,
		UncoveredLines:   []int{20, 21, 22, 23},
	}
}

// simulatePythonTests simulates Python test execution
func (t *TestAgent) simulatePythonTests(result *TestResult) {
	result.Tests = []TestCase{
		{Name: "test_basic_functionality", Status: "passed", Duration: 0.001, Line: 5},
		{Name: "test_edge_cases", Status: "passed", Duration: 0.001, Line: 9},
		{Name: "test_error_handling", Status: "passed", Duration: 0.002, Line: 13},
		{Name: "test_parametrized[1-2]", Status: "passed", Duration: 0.001, Line: 18},
		{Name: "test_parametrized[2-4]", Status: "passed", Duration: 0.001, Line: 18},
		{Name: "test_parametrized[3-6]", Status: "passed", Duration: 0.001, Line: 18},
	}
	result.Duration = 0.007
	result.Coverage = &Coverage{
		LineCoverage:     92.0,
		BranchCoverage:   88.0,
		FunctionCoverage: 95.0,
		UncoveredLines:   []int{25, 26},
	}
}

// GetTestSummary returns summary of all test results
func (t *TestAgent) GetTestSummary() map[string]interface{} {
	totalTests := 0
	totalPassed := 0
	totalFailed := 0
	totalSkipped := 0

	for _, result := range t.TestResults {
		totalTests += result.TotalTests
		totalPassed += result.Passed
		totalFailed += result.Failed
		totalSkipped += result.Skipped
	}

	passRate := 0.0
	if totalTests > 0 {
		passRate = float64(totalPassed) / float64(totalTests) * 100
	}

	return map[string]interface{}{
		"total_tests":     totalTests,
		"passed":          totalPassed,
		"failed":          totalFailed,
		"skipped":         totalSkipped,
		"pass_rate":       fmt.Sprintf("%.2f%%", passRate),
		"test_files":      len(t.TestResults),
		"supported_langs": t.SupportedLangs,
		"frameworks":      t.TestFrameworks,
	}
}

// GetTestConfig returns test configuration for a language
func (t *TestAgent) GetTestConfig(language string, sourceFile string) (*TestConfig, error) {
	config := &TestConfig{
		Language:   language,
		SourceFile: sourceFile,
	}

	switch language {
	case "C++":
		config.TestFile = strings.TrimSuffix(sourceFile, filepath.Ext(sourceFile)) + "_test.cpp"
		config.TestFramework = "Catch2"
		config.BuildCommand = "g++ -std=c++17 -o test_runner " + config.TestFile
		config.RunCommand = "./test_runner"
	case "Go":
		config.TestFile = strings.TrimSuffix(sourceFile, filepath.Ext(sourceFile)) + "_test.go"
		config.TestFramework = "testing"
		config.BuildCommand = "go test -c"
		config.RunCommand = "go test -v"
	case "R":
		config.TestFile = "tests/testthat.R"
		config.TestFramework = "testthat"
		config.BuildCommand = ""
		config.RunCommand = "Rscript -e 'testthat::test_dir(\"tests\")'"
	case "Python":
		config.TestFile = "tests/test_" + filepath.Base(sourceFile)
		config.TestFramework = "pytest"
		config.BuildCommand = ""
		config.RunCommand = "pytest -v " + config.TestFile
	default:
		return nil, fmt.Errorf("unsupported language: %s", language)
	}

	return config, nil
}

// extractFunctionNames parses source code to extract function/method names
func extractFunctionNames(content string) []string {
	functions := make([]string, 0)
	lines := strings.Split(content, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		// Match common function patterns
		// Go: func Name(
		if strings.HasPrefix(line, "func ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				funcName := parts[1]
				// Remove receiver if present (e.g., (t *Type) MethodName)
				if strings.HasPrefix(funcName, "(") {
					continue // Skip receiver definition line
				}
				// Extract just the name before ( or generic parameters
				if idx := strings.Index(funcName, "("); idx > 0 {
					funcName = funcName[:idx]
				}
				if idx := strings.Index(funcName, "["); idx > 0 {
					funcName = funcName[:idx]
				}
				if funcName != "" && funcName != "main" {
					functions = append(functions, funcName)
				}
			}
		}
		// C++: return_type Name( or void Name(
		if !strings.Contains(line, "//") && strings.Contains(line, "(") {
			// Check for common C++ function patterns
			if !strings.HasPrefix(line, "#") && !strings.HasPrefix(line, "//") {
				// Try to detect function declarations
				beforeParen := line[:strings.Index(line, "(")]
				parts := strings.Fields(beforeParen)
				if len(parts) >= 2 {
					// Last part before ( should be function name
					funcName := parts[len(parts)-1]
					if !strings.Contains(funcName, "*") && !strings.Contains(funcName, "&") {
						functions = append(functions, funcName)
					}
				}
			}
		}
	}

	return functions
}

func main() {
	agent := NewTestAgent()

	if len(os.Args) > 1 {
		command := os.Args[1]

		switch command {
		case "generate":
			if len(os.Args) < 4 {
				fmt.Println("Usage: test-agent generate <source-file> <language>")
				os.Exit(1)
			}
			sourceFile := os.Args[2]
			language := os.Args[3]

			testCode, err := agent.GenerateTests(sourceFile, language)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", err)
				os.Exit(1)
			}
			fmt.Println(testCode)

		case "run":
			if len(os.Args) < 4 {
				fmt.Println("Usage: test-agent run <test-file> <language>")
				os.Exit(1)
			}
			testFile := os.Args[2]
			language := os.Args[3]

			result, err := agent.RunTests(testFile, language)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", err)
				os.Exit(1)
			}
			json.NewEncoder(os.Stdout).Encode(result)

		case "config":
			if len(os.Args) < 4 {
				fmt.Println("Usage: test-agent config <source-file> <language>")
				os.Exit(1)
			}
			sourceFile := os.Args[2]
			language := os.Args[3]

			config, err := agent.GetTestConfig(language, sourceFile)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", err)
				os.Exit(1)
			}
			json.NewEncoder(os.Stdout).Encode(config)

		case "summary":
			summary := agent.GetTestSummary()
			json.NewEncoder(os.Stdout).Encode(summary)

		default:
			fmt.Println("Test Agent - Test Generation and Execution")
			fmt.Println("Supported languages:", strings.Join(agent.SupportedLangs, ", "))
			fmt.Println("Test frameworks:", agent.TestFrameworks)
			fmt.Println("\nCommands:")
			fmt.Println("  generate <source> <lang>  - Generate tests for source file")
			fmt.Println("  run <test-file> <lang>    - Run tests")
			fmt.Println("  config <source> <lang>    - Get test configuration")
			fmt.Println("  summary                   - Get test summary")
		}
	} else {
		fmt.Println("Test Agent - Test Generation and Execution")
		fmt.Println("Supported languages:", strings.Join(agent.SupportedLangs, ", "))
		fmt.Println("\nUsage: test-agent <command> [args]")
	}
}

var _ = filepath.Join // Ensure filepath is used
